### ISSUE TITLE
phone crash going alltvshows then allmovies open one movie

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#102]
On phone, open alltvshows and a tvshow then go back to allmovies, open a movie, it is briefly displayed and then application crashes. Surprisingly crash is located in BrowserWithShowHeader.java.
Side note: this mirgration to support libraries for LoaderManager&cursors is a bumpy road...
```
2019-04-13 20:36:00.403 3801-3801/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.courville.nova, PID: 3801
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.app.FragmentActivity.invalidateOptionsMenu()' on a null object reference
        at com.archos.mediacenter.video.browser.BrowserByIndexedVideos.BrowserWithShowHeader.onLoadFinished(BrowserWithShowHeader.java:258)
        at com.archos.mediacenter.video.browser.BrowserByIndexedVideos.BrowserWithShowHeader.onLoadFinished(BrowserWithShowHeader.java:66)
        at android.support.v4.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at android.support.v4.content.Loader.deliverResult(Loader.java:132)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:109)
        at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:41)
        at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
        at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
        at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by courville** [comment]
Issue avoided...
