### ISSUE TITLE
phone: crash when switching off the screen and on in All TV shows view (or another)

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#105]
Go in All TV shows then switch off screen (app goes in background) switch it on again and there is a crash:
```
2019-04-14 16:45:35.418 30124-30124/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.courville.nova, PID: 30124
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.courville.nova/com.archos.mediaprovider.video.VideoStoreImportService }: app is in background uid UidRecord{8dc31ff u0a323 TPSL bg:+1m17s445ms idle change:cached procs:2 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at com.archos.mediaprovider.video.VideoStoreImportService.start(VideoStoreImportService.java:233)
        at com.archos.mediaprovider.video.VideoProvider$5.onForeGroundState(VideoProvider.java:1387)
        at com.archos.mediacenter.utils.AppState.notifyListener(AppState.java:76)
        at com.archos.mediacenter.utils.AppState$1.onActivityStarted(AppState.java:112)
        at android.app.Application.dispatchActivityStarted(Application.java:230)
        at android.app.Activity.onStart(Activity.java:1278)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7165)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by courville** [comment]
Not able to reproduce anymore (hem!).
