### ISSUE TITLE
[Bug]: APP crashes when opened

### ISSUE THREAD

**Issue by kajdo** [nova-video-player/aos-AVP#1293]
### Problem description

I installed all versions i found (with fresh de-installation cycle before installing another version) and open it on samsung galaxy s7 fe (android 14), the splash screen flashes but then the app stops (app closes - back to homescreen)

some version gave me the hint, that the version of the app is "too old for the android version" (which i doubt because i run it on android 14 on my pixel 6 as well

### Steps to reproduce the issue

install on samsung galaxy tab s7 FE (Android 14) from
- fdroid (fdroid repo) or
- fdroid (izzy repo) or
- git - armv7 version or
- git - armv8 version or
- git - arm universal version

open app

### Expected behavior

app opens 

### Your phone/tablet/androidTV model

samsung galaxy tab s7 fe

### Operating system version

android 14

### Application version and app store

fdroid 6.2.95

### Additional system information

also tried fdroid 6.2.93 and fdroid 6.2.90 - same behaviour

**Comment by kajdo** [comment]
tried also google play version - same outcome

this is the error (sorry in german) which I get with Izzy Version 6.3.3-20241006.1133
Diese App ist nicht mit der neuesten Android-Version kompatibel. Suche nach einem Update oder wende dich an den App-Entwickler.

**Comment by courville** [comment]
@kajdo, is the galaxy tab s7 fe firmware running on the tablet a genuine samsung one?

Could you please extract nova logs (adb logcat cf.  https://github.com/nova-video-player/aos-AVP/wiki/Debugging) when the crash is happening. This would help me understanding what is happening.

**Comment by kajdo** [comment]
> @kajdo, is the galaxy tab s7 fe firmware running on the tablet a genuine samsung one?
> 
> Could you please extract nova logs (adb logcat cf.  https://github.com/nova-video-player/aos-AVP/wiki/Debugging) when the crash is happening. This would help me understanding what is happening.

yes its not touched ... that's why i was confused because i thought if it runs on my pixel with graphene, it must be a nobrainer on the tab

thx for the adb link, will try to get more info and provide it

**Comment by kajdo** [comment]
the logback.xml i created and pushed did not create a nova.log
```
adb: error: failed to stat remote object '/sdcard/Download/org.courville.nova/nova.log': No such file or directory
```

i did `adb logcat | grep org.courville.nova | tee nova.log` to get some information (see attachement)
[nova.log](https://github.com/user-attachments/files/17378122/nova.log)

**Comment by courville** [comment]
Thanks for investingating (forget the logback.xml for now).
Could you please send the full `adb logcat` without the grep to capture the crash report (it should be visible)?

**Comment by kajdo** [comment]
@courville here we go ... now with cleared logcat before getting the new one
[nova_current.log](https://github.com/user-attachments/files/17383676/nova_current.log)

**Comment by courville** [comment]
Thanks here is the crash log:
```
10-15 21:13:48.975  7559  7559 I System.out: 21:13:48,975 |-INFO in ch.qos.logback.classic.joran.action.FindIncludeAction - Path found [file:/storage/emulated/0/Android/data/org.courville.nova/files/Android/data/org.courville.nova/files/logback/logback.xml]
10-15 21:13:48.976  7559  7559 I System.out: 21:13:48,976 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@f1fda00 - Adding [file:/storage/emulated/0/Android/data/org.courville.nova/files/Android/data/org.courville.nova/files/logback/logback.xml] to configuration watch list.
10-15 21:13:48.977  7559  7559 W System.err: org.xmlpull.v1.XmlPullParserException: Attr.value missing f. TRACE (position:START_TAG <SubtitlesDownloaderActivity: TRACE='com.archos.mediaprovider.video.RemoteStateService'>@61:37 in java.io.InputStreamReader@510807e) 
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.org.kxml2.io.KXmlParser.checkRelaxed(KXmlParser.java:305)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1132)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.xmlpull.v1.sax2.Driver.parseSubTree(Driver.java:449)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.xmlpull.v1.sax2.Driver.parse(Driver.java:340)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.action.IncludeAction.processInclude(Unknown Source:24)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.classic.joran.action.FindIncludeAction.end(Unknown Source:55)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source:23)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source:84)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:32)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.impl.LoggerServiceProvider.initializeLoggerContext(Unknown Source:7)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.impl.LoggerServiceProvider.initialize(Unknown Source:12)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.bind(SourceFile:196)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.performInitialization(SourceFile:183)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.getProvider(SourceFile:486)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.getILoggerFactory(SourceFile:472)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.getLogger(SourceFile:421)
10-15 21:13:48.978  7559  7559 W System.err: 	at org.slf4j.LoggerFactory.getLogger(SourceFile:447)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.archos.mediaprovider.video.VideoProvider.<clinit>(SourceFile:86)
10-15 21:13:48.978  7559  7559 W System.err: 	at java.lang.Class.newInstance(Native Method)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
10-15 21:13:48.978  7559  7559 W System.err: 	at androidx.core.app.CoreComponentFactory.instantiateProvider(SourceFile:66)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8488)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8004)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7690)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.os.Looper.loopOnce(Looper.java:230)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.os.Looper.loop(Looper.java:319)
10-15 21:13:48.978  7559  7559 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8934)
10-15 21:13:48.978  7559  7559 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-15 21:13:48.978  7559  7559 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-15 21:13:48.979  7559  7559 I System.out: 21:13:48,978 |-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@79188f5 - XML_PARSING - Parsing fatal error on line 61 and column 37 org.xmlpull.v1.XmlPullParserException: Attr.value missing f. TRACE (position:START_TAG <SubtitlesDownloaderActivity: TRACE='com.archos.mediaprovider.video.RemoteStateService'>@61:37 in java.io.InputStreamReader@510807e) 
10-15 21:13:48.979  7559  7559 I System.out: 	at org.xml.sax.SAXParseException: parsing error: org.xmlpull.v1.XmlPullParserException: Attr.value missing f. TRACE (position:START_TAG <SubtitlesDownloaderActivity: TRACE='com.archos.mediaprovider.video.RemoteStateService'>@61:37 in java.io.InputStreamReader@510807e) 
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.xmlpull.v1.sax2.Driver.parseSubTree(Driver.java:452)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.xmlpull.v1.sax2.Driver.parse(Driver.java:340)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.action.IncludeAction.processInclude(Unknown Source:24)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.classic.joran.action.FindIncludeAction.end(Unknown Source:55)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source:23)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source:84)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(SourceFile:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:32)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.impl.LoggerServiceProvider.initializeLoggerContext(Unknown Source:7)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.impl.LoggerServiceProvider.initialize(Unknown Source:12)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.bind(SourceFile:196)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.performInitialization(SourceFile:183)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.getProvider(SourceFile:486)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(SourceFile:472)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.getLogger(SourceFile:421)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at org.slf4j.LoggerFactory.getLogger(SourceFile:447)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at com.archos.mediaprovider.video.VideoProvider.<clinit>(SourceFile:86)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at java.lang.Class.newInstance(Native Method)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at androidx.core.app.CoreComponentFactory.instantiateProvider(SourceFile:66)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread.installProvider(ActivityThread.java:8488)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8004)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7690)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.os.Looper.loopOnce(Looper.java:230)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.os.Looper.loop(Looper.java:319)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at android.app.ActivityThread.main(ActivityThread.java:8934)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at java.lang.reflect.Method.invoke(Native Method)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-15 21:13:48.979  7559  7559 I System.out: 	at 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by courville** [comment]
@kajdo: could you try to do
```
adb shell rm /storage/emulated/0/Android/data/org.courville.nova/files/Android/data/org.courville.nova/files/logback/logback.xml
```

**Comment by kajdo** [comment]
done

forced closed nova (just in case a background task is running), cleared logs (`adb logcat -c`) and re-testet
  
[nova_fresh.log](https://github.com/user-attachments/files/17383771/nova_fresh.log)

**Comment by kajdo** [comment]
found in both logs:
```
10-15 21:41:47.654 25850 26377 D NetdEventListenerService: DNS Requested by 100, 10437, 50
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.693 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.694 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
10-15 21:41:47.695 10670 10670 E LocaleConfigParser: Language attribute is missing in locales config
```

maybe that's the issue?

for the exceptions about vpn - i run the test with tailscale on and off (on the phone i use tailscale as well to remote access my samba shares and it works)

on the tab the crash happens with vpn on and of .... also tried to disable flight mode - no change in behaviour

mentioning the locale thing because it also happens "around" nova
![image](https://github.com/user-attachments/assets/7ac460eb-1b48-4c34-93da-c20614fc9a5e)

**Comment by courville** [comment]
No it is not the `LocaleConfigParser`. Somehow we just get:
```
10-15 21:41:47.747 25850 29588 I ActivityManager: Process org.courville.nova (pid 10670) has died: fg  TOP (197,788)
```
No other meaningful crash log.

**Comment by kajdo** [comment]
ah - didn't see that :( .... not sure if i could check more

would love to see it working on the tab, because it handles the "download from jellyfin" usecase perfectly, can simply download from the samba share jellyfin is taking the videos from and spend a couple of hours offline

please let me know if i can support somehow

**Comment by courville** [comment]
Is the behavior experienced to get a blue screen when nova is launched without anything and then a while after a force close?

EDIT: if this is the case please try to reboot your tablet (I guess you already tried).

**Comment by kajdo** [comment]
the tablet is configured to reboot nightly (and it did yesterday), so i did not try to manual reboot

still - i prepared everything right now 
- rebooted the tab
- started screenrecording to show you the behaviour
- adb logcat -c
- started to log the logcat
- forced closed (just to be sure no background task is running) nova player
- started nova player
- expected crash, but **it works**

what i did realize during reboot of the tablet - it started a "UI Optimization for APPs" during boot (which i'm quite certain, that this isn't happening during nightly reboots)

maybe a manual reboot on samsung != an automatic reboot .... i still feel a bit stupid, but in my defense - not using windows for years kind of makes you forgetting about this whole reboot thingy

thx for your support -- please consider this issue as closed ... and maybe this writeup helps someone in future ;)

happy i can use nova on the tab now :)
