### ISSUE TITLE
Q DP3 nova crash on phones

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#131]
```
2019-05-08 11:01:35.261 12997-13067/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: ImportWorker
    Process: org.courville.nova, PID: 12997
    java.lang.IllegalArgumentException: Invalid column group_concat(_id)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:934)
        at android.content.ContentResolver.query(ContentResolver.java:872)
        at android.content.ContentResolver.query(ContentResolver.java:830)
        at com.archos.mediaprovider.video.VideoStoreImportImpl.getRemoteIdList(VideoStoreImportImpl.java:574)
        at com.archos.mediaprovider.video.VideoStoreImportImpl.doFullImport(VideoStoreImportImpl.java:88)
        at com.archos.mediaprovider.video.VideoStoreImportService.doImport(VideoStoreImportService.java:338)
        at com.archos.mediaprovider.video.VideoStoreImportService.handleMessage(VideoStoreImportService.java:286)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by courville** [comment]
Cf. https://github.com/nova-video-player/aos-MediaLib/commit/621f69160bebb58ac271244c1d710340b36124be

**Comment by courville** [comment]
This is on getRemoteIdList thus probably located on MediaStore.java       
```
Cursor c = cr.query(MediaStore.Files.getContentUri("external"), REMOTE_LIST_PROJECTION, null, null, null);
```
and `REMOTE_LIST_PROJECTION="group_concat(" + BaseColumns._ID + ")"`

**Comment by courville** [comment]
Check that projection is indeed against a list of "allowed" columns cf. https://stackoverflow.com/questions/4702206/illegalargumentexception-invalid-column
I.e. content provider's projection map.

**Comment by phhusson** [comment]
Issue is that packages/providers/MediaProvider/.../MediaProvider.java enabled https://developer.android.com/reference/android/database/sqlite/SQLiteQueryBuilder#setStrict(boolean) true

So I don't see any workaround other than implementing group_concat manually by requesting only for _ID, and concatenating results from cursor

**Comment by courville** [comment]
Fix provided works but surprisingly not all the files are imported on Android Q (works on Android P):
```
2019-05-09 22:16:32.133 8527-8585/org.courville.nova D/AMXVideoStoreImportImpl: full import +:308 -:0 0=>308
```
308 instead of 519...
