### ISSUE TITLE
tvshow by date crash

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#132]
Entering the view makes nova crash:
```
05-08 21:11:44.356  7518  7518 D AllMoviesIconManager: buildNewBitmap took 27 | 30
05-08 21:11:44.433  7518  7518 E WindowManager:
05-08 21:11:44.433  7518  7518 E WindowManager: android.view.WindowLeaked: Activity com.archos.mediacenter.video.leanback.MainActivityLeanback has l
eaked window DecorView@1bca5ae[MainActivityLeanback] that was originally added here
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.Dialog.show(Dialog.java:333)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.AlertDialog$Builder.show(AlertDialog.java:1125)
05-08 21:11:44.433  7518  7518 E WindowManager:         at com.archos.mediacenter.video.DensityTweak.showDialog(DensityTweak.java:173)
05-08 21:11:44.433  7518  7518 E WindowManager:         at com.archos.mediacenter.video.DensityTweak.showDensityChoiceIfNeeded(DensityTweak.java:105)
05-08 21:11:44.433  7518  7518 E WindowManager:         at com.archos.mediacenter.video.leanback.MainActivityLeanback.onCreate(MainActivityLeanback.java:67)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.Activity.performCreate(Activity.java:7213)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.Activity.performCreate(Activity.java:7204)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1287)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3011)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3166)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.os.Looper.loop(Looper.java:193)
05-08 21:11:44.433  7518  7518 E WindowManager:         at android.app.ActivityThread.main(ActivityThread.java:6971)
05-08 21:11:44.433  7518  7518 E WindowManager:         at java.lang.reflect.Method.invoke(Native Method)
05-08 21:11:44.433  7518  7518 E WindowManager:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 21:11:44.433  7518  7518 E WindowManager:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
05-08 21:11:44.450   128   406 W WindowManager: Failed looking up window callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5545 com.android.server.wm.WindowManagerService.removeWindow:1649 com.android.server.wm.Session.remove:226 
--------- beginning of crash
05-08 21:11:50.294  7518  7518 E AndroidRuntime: FATAL EXCEPTION: main
05-08 21:11:50.294  7518  7518 E AndroidRuntime: Process: org.courville.nova, PID: 7518
05-08 21:11:50.294  7518  7518 E AndroidRuntime: java.util.concurrent.RejectedExecutionException: Task androidx.loader.content.ModernAsyncTask$3@490f987 rejected from java.util.concurrent.ThreadPoolExecutor@32b90b4[Running, pool size = 128, active threads = 128, queued tasks = 9, completed tasks = 73]
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:452)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:228)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:156)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.Loader.forceLoad(Loader.java:347)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.CursorLoader.onStartLoading(CursorLoader.java:158)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.Loader.startLoading(Loader.java:285)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:376)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:181)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData.observe(LiveData.java:185)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at com.archos.mediacenter.video.leanback.VideosByFragment.loadCategoriesRows(VideosByFragment.java:298)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at com.archos.mediacenter.video.leanback.VideosByFragment.onLoadFinished(VideosByFragment.java:219)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at com.archos.mediacenter.video.leanback.VideosByFragment.onLoadFinished(VideosByFragment.java:44)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.Loader.deliverResult(Loader.java:132)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6971)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-08 21:11:50.294  7518  7518 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
```

**Comment by courville** [comment]
invalid cannot reproduce with clean build
