### ISSUE TITLE
non recoverable app crash for a while

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#133]
On Android TV: open app, go through indexing large folder on remote share with tvshows, get back to main screen, open tvshow by date, frequent refresh causes app to crash and cannot open app again for a while:
```
2019-05-09 22:53:22.787 5867-5907/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: Thread-8
    Process: org.courville.nova, PID: 5867
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:130)
        at android.content.Intent.<init>(Intent.java:5780)
        at com.archos.filecorelibrary.FileUtils.showNotification(FileUtils.java:327)
        at com.archos.mediascraper.AutoScrapeService$3.run(AutoScrapeService.java:272)
```

**Comment by courville** [comment]
TVshows by genre when the crash happens:
```
2019-05-09 23:07:24.842 6882-7024/org.courville.nova E/SQLiteLog: (9) statement aborts at 226: [SELECT _data, s_name AS name, s_id AS _id, scraper_name, s_cover, e_season, s_premiered, s_studios, s_plot, e_actors, s_rating, max(date_added) AS max_date, COUNT(DISTINCT e_season) A
2019-05-09 23:07:24.842 6882-7066/org.courville.nova E/SQLiteLog: (9) statement aborts at 21: [SELECT _data, s_name AS name, s_id AS _id, scraper_name, s_cover, e_season, s_premiered, s_studios, s_plot, e_actors, s_rating, max(date_added) AS max_date, COUNT(DISTINCT e_season) AS
2019-05-09 23:07:24.843 6882-7016/org.courville.nova E/SQLiteLog: (9) statement aborts at 151: [SELECT _data, s_name AS name, s_id AS _id, scraper_name, s_cover, e_season, s_premiered, s_studios, s_plot, e_actors, s_rating, max(date_added) AS max_date, COUNT(DISTINCT e_season) A
2019-05-09 23:07:24.893 6882-6882/org.courville.nova D/TvshowsByFragment: No difference found in the category list
2019-05-09 23:07:24.920 6882-7070/org.courville.nova E/SQLiteLog: (9) statement aborts at 50: [SELECT
           _id,
           name_genre AS name,
           group_concat( s_id ) AS list,
           group_concat( s_po_large_file ) AS po_file_list,
           count( s_id ) AS number
      FROM  (
        
2019-05-09 23:07:24.922 6882-7047/org.courville.nova E/SQLiteLog: (9) statement aborts at 74: [SELECT _data, s_name AS name, s_id AS _id, scraper_name, s_cover, e_season, s_premiered, s_studios, s_plot, e_actors, s_rating, max(date_added) AS max_date, COUNT(DISTINCT e_season) AS
2019-05-09 23:07:24.922 6882-6992/org.courville.nova E/SQLiteLog: (9) statement aborts at 21: [SELECT _data, s_name AS name, s_id AS _id, scraper_name, s_cover, e_season, s_premiered, s_studios, s_plot, e_actors, s_rating, max(date_added) AS max_date, COUNT(DISTINCT e_season) AS
2019-05-09 23:07:24.993 6882-6882/org.courville.nova D/TvshowsByFragment: No difference found in the category list
2019-05-09 23:07:25.190 6882-6882/org.courville.nova D/TvshowsByFragment: No difference found in the category list
2019-05-09 23:07:25.294 6882-6882/org.courville.nova D/AndroidRuntime: Shutting down VM
2019-05-09 23:07:25.298 6882-6882/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.courville.nova, PID: 6882
    java.util.concurrent.RejectedExecutionException: Task androidx.loader.content.ModernAsyncTask$3@5347a12 rejected from java.util.concurrent.ThreadPoolExecutor@75a5e3[Running, pool size = 128, active threads = 2, queued tasks = 3, completed tasks = 1460]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
        at androidx.loader.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:452)
        at androidx.loader.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:228)
        at androidx.loader.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:156)
        at androidx.loader.content.Loader.forceLoad(Loader.java:347)
        at androidx.loader.content.Loader.onContentChanged(Loader.java:512)
        at androidx.loader.content.Loader$ForceLoadContentObserver.onChange(Loader.java:69)
        at android.database.ContentObserver.onChange(ContentObserver.java:130)
        at android.database.ContentObserver.onChange(ContentObserver.java:145)
        at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-05-09 23:07:25.301 6882-6882/org.courville.nova I/Process: Sending signal. PID: 6882 SIG: 9
```

**Comment by courville** [comment]
LoaderManager crash should be fixed now through try/catch and own executor for VideoLoader/CursorLoader with longer queue.
The getPackageName() crash is still not resolved.
