### ISSUE TITLE
[Bug]: 6.3.15 won't start on FireTV Stick 4K 1st gen even with a clean install

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#1349]
### Problem description

As the title says, 6.3.15 refuses to start. I get a blue screen and then it crashes to the FireTV launcher, over and over. 

### Steps to reproduce the issue

1) Install 6.3.15
2) See it crashes to launcher after showing the blue background momentarily instead of starting normally
3) Clear data to be rule out previous install
4) 6.3.15 continues to crash to launcher when opened

@courville I'm sure you can see the Sentry logs on your end

### Your phone/tablet/androidTV model

FireTV 4K Stick 1st gen

### Operating system version

FireOS6

### Application version and app store

6.3.15

**Comment by courville** [comment]
Thx for the heads up: I disabled the release for now pending investigation.

EDIT: probably linked to
```
java.lang.IllegalArgumentException: Invalid column null
    at android.database.sqlite.SQLiteQueryBuilder.computeSingleProjectionOrThrow(SQLiteQueryBuilder.java:1024)
    at android.database.sqlite.SQLiteQueryBuilder.computeProjection(SQLiteQueryBuilder.java:995)
    at android.database.sqlite.SQLiteQueryBuilder.buildQuery(SQLiteQueryBuilder.java:800)
    at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:506)
    at com.archos.mediaprovider.video.VideoProvider.query(VideoProvider.java:340)
    at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
    at android.content.ContentResolver.query(ContentResolver.java:532)
    at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:127)
    at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
    at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
    at com.archos.mediacenter.video.browser.UpdateRecommendationsService.update(UpdateRecommendationsService.java:136)
    at com.archos.mediacenter.video.browser.UpdateRecommendationsService.onHandleIntent(UpdateRecommendationsService.java:199)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

See https://github.com/nova-video-player/aos-AVP/issues/1350

**Comment by courville** [comment]
@Pentaphon, could you try if this release is any better https://drive.google.com/file/d/1h6wh0PUNSooZyaVFtNTI6VdAdCwP_9pv/view?usp=drive_link ?
What is strange is that the stacktrace references code that could be an issue but that has been there for a very long time.

**Comment by Pentaphon** [comment]
>could you try if this release is any better https://drive.google.com/file/d/1h6wh0PUNSooZyaVFtNTI6VdAdCwP_9pv/view?usp=drive_link ? What is strange is that the stacktrace references code that could be an issue but that has been there for a very long time.

@courville Yep, that fixed it. Working as intended so far while scraping and playing video.
