### ISSUE TITLE
exceeding thread pool using tvshow by date causing crash

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#141]
When using the following piconas.zip small pool of fake files, opening the tvshows by date makes application crash systematically on my end:
```
2019-05-17 23:07:09.335 11106-11106/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.courville.nova, PID: 11106
    java.util.concurrent.RejectedExecutionException: Task androidx.loader.content.ModernAsyncTask$3@c309197 rejected from java.util.concurrent.ThreadPoolExecutor@ed42f84[Running, pool size = 128, active threads = 128, queued tasks = 10, completed tasks = 51]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2085)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at androidx.loader.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:452)
        at androidx.loader.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:228)
        at androidx.loader.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java:156)
        at androidx.loader.content.Loader.forceLoad(Loader.java:347)
        at androidx.loader.content.CursorLoader.onStartLoading(CursorLoader.java:158)
        at androidx.loader.content.Loader.startLoading(Loader.java:285)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onActive(LoaderManagerImpl.java:77)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:418)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:376)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:181)
        at androidx.lifecycle.LiveData.observe(LiveData.java:185)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
        at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
        at androidx.loader.app.LoaderManagerImpl.restartLoader(LoaderManagerImpl.java:447)
        at com.archos.mediacenter.video.leanback.VideosByFragment.loadCategoriesRows(VideosByFragment.java:298)
        at com.archos.mediacenter.video.leanback.VideosByFragment.onLoadFinished(VideosByFragment.java:219)
        at com.archos.mediacenter.video.leanback.VideosByFragment.onLoadFinished(VideosByFragment.java:44)
        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at androidx.loader.content.Loader.deliverResult(Loader.java:132)
        at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
        at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
        at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
        at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
        at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
2019-05-17 23:07:09.345 11106-11106/org.courville.nova I/Process: Sending signal. PID: 11106 SIG: 9
```
Seems that we are exceeding thread pool.
[piconas.zip](https://github.com/nova-video-player/aos-AVP/files/3193125/piconas.zip)

**Comment by courville** [comment]
@persi-persu would you have an idea there?

**Comment by courville** [comment]
If there are more than 128 weeks to display it will happen.
It does not in all other views because alphabetical is 26 or so, years since movies have been created is less than 128 (close?) etc... Need to evolve the method used...

**Comment by courville** [comment]
Solution would be to go through an executor that limits the number of parallel threads.
https://examples.javacodegeeks.com/core-java/util/concurrent/rejectedexecutionexception/java-util-concurrent-rejectedexecutionexception-how-to-solve-rejectedexecutionexception/
I thought that AsyncTaskLoader would do it...

**Comment by courville** [comment]
Perhaps on top of "do not crash" patch, add a way to detect empty line to reload?
