### ISSUE TITLE
Android Q: MediaStore does not contain avi files?

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#162]
All avi files are not VideoStoreImported on Android Q devices and thus not indexed.

**Comment by courville** [comment]
Note that MediaStore.MediaColumns.DATA is deprecated for API29 cf. https://developer.android.com/reference/android/provider/MediaStore.MediaColumns

**Comment by courville** [comment]
Strangely enough currently `MediaStore.Files.getContentUri("external")` does not show any avi files for now. This can be checked via `adb shell content query --uri "content://media/external/file"  --projection name:_data`.

**Comment by courville** [comment]
Adding an avi file via MTP produces this warning:
```
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: Ignoring troubled file: /storage/emulated/0/Movies/Merlin_(2008)-s01e06-A_Remedy_to_Cure_All_Ills.avi
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.scanItemVideo(ModernMediaScanner.java:674)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.scanItem(ModernMediaScanner.java:459)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.access$500(ModernMediaScanner.java:117)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner$Scan.visitFile(ModernMediaScanner.java:374)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner$Scan.visitFile(ModernMediaScanner.java:206)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at java.nio.file.Files.walkFileTree(Files.java:2670)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at java.nio.file.Files.walkFileTree(Files.java:2742)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner$Scan.run(ModernMediaScanner.java:241)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.scanFile(ModernMediaScanner.java:173)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.MediaProvider.call(MediaProvider.java:4047)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.content.ContentProvider.call(ContentProvider.java:2142)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:558)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.content.ContentProviderClient.call(ContentProviderClient.java:546)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.provider.MediaStore.scan(MediaStore.java:3597)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.provider.MediaStore.scanFile(MediaStore.java:3574)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.mtp.MtpDatabase.endSendObject(MtpDatabase.java:423)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.mtp.MtpServer.native_run(Native Method)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.mtp.MtpServer.run(MtpServer.java:116)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at java.lang.Thread.run(Thread.java:919)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:142)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	at com.android.providers.media.scan.ModernMediaScanner.scanItemVideo(ModernMediaScanner.java:639)
06-11 21:44:31.579  3447  7046 W ModernMediaScanner: 	... 19 more
```
And the file appears on MTP but not listed in MediaStore.Files...

**Comment by courville** [comment]
Issue not fixed in Q DP5.

**Comment by courville** [comment]
Issue reported here https://issuetracker.google.com/issues/136774034

**Comment by courville** [comment]
Issue still present in DP6.
Problem is clearer: after scanning of a valid avi file by ModernMediaScanner which fails, this file is discarded even from the list of files in the Media Files database.
Any other file like a random.bin would be listed with mime-type application/octet-stream (non scanned).
This is an Android Q bug (cf. discussion on https://issuetracker.google.com/issues/136774034).
Dirty patch proposed.
I would be ok to have the avi file if not scanned correctly not listed in the Video Files but still be present in the Files containing all the file.

**Comment by courville** [comment]
Android 10 is out and... it seems now to work, I can import avi files.
