### ISSUE TITLE
trakt authentication fails on google play release 2087006

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#164]
```
06-08 15:55:31.570 I/.courville.nov(14532): Rejecting re-init on previously-failed class java.lang.Class<org.apache.oltu.oauth2.common.utils.JSONUtils>: java.lang.VerifyError: Verifier rejected class org.apache.oltu.oauth2.common.utils.JSONUtils: java.lang.String org.apache.oltu.oauth2.common.utils.JSONUtils.buildJSON(j
ava.util.Map) failed to verify: java.lang.String org.apache.oltu.oauth2.common.utils.JSONUtils.buildJSON(java.util.Map): [0x5] 'this' argument 'Precise Reference: org.json.JSONStringer' not instance of 'Reference: org.json.JSONWriter' (declaration of 'org.apache.oltu.oauth2.common.utils.JSONUtils' appears in base.apk)
06-08 15:55:31.570 I/.courville.nov(14532):   at java.util.Map org.apache.oltu.oauth2.common.utils.JSONUtils.parseJSON(java.lang.String) (SourceFile:55)
06-08 15:55:31.570 I/.courville.nov(14532):   at void org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse.setBody(java.lang.String) (SourceFile:68)
06-08 15:55:31.570 I/.courville.nov(14532):   at void org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(java.lang.String, java.lang.String, int) (SourceFile:56)
06-08 15:55:31.570 I/.courville.nov(14532):   at void org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(java.lang.String, java.lang.String, int) (SourceFile:52)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthClientResponse org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(java.lang.String, java.lang.String, int, java.lang.Class) (SourceFile:60)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthClientResponse com.uwetrottmann.trakt.v2.TraktHttpClient.execute(org.apache.oltu.oauth2.client.request.OAuthClientRequest, java.util.Map, java.lang.String, java.lang.Class) (SourceFile:73)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse org.apache.oltu.oauth2.client.OAuthClient.accessToken(org.apache.oltu.oauth2.client.request.OAuthClientRequest, java.lang.String, java.lang.Class) (SourceFile:65)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse org.apache.oltu.oauth2.client.OAuthClient.accessToken(org.apache.oltu.oauth2.client.request.OAuthClientRequest, java.lang.Class) (SourceFile:55)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse org.apache.oltu.oauth2.client.OAuthClient.accessToken(org.apache.oltu.oauth2.client.request.OAuthClientRequest) (SourceFile:71)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse com.uwetrottmann.trakt.v2.TraktV2.getAccessToken(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (SourceFile:162)
06-08 15:55:31.570 I/.courville.nov(14532):   at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse com.archos.mediacenter.utils.trakt.Trakt.getAccessToken(java.lang.String) (SourceFile:264)
06-08 15:55:31.570 I/.courville.nov(14532):   at java.lang.Object com.archos.mediacenter.video.utils.TraktSigninDialogPreference$1$1.doInBackground(java.lang.Object[]) (SourceFile:80)
06-08 15:55:31.570 I/.courville.nov(14532):   at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:333)
06-08 15:55:31.570 I/.courville.nov(14532):   at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)
06-08 15:55:31.570 I/.courville.nov(14532):   at void android.os.AsyncTask$SerialExecutor$1.run() (AsyncTask.java:245)
06-08 15:55:31.570 I/.courville.nov(14532):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1167)
06-08 15:55:31.570 I/.courville.nov(14532):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:641)
06-08 15:55:31.570 I/.courville.nov(14532):   at void java.lang.Thread.run() (Thread.java:764)
06-08 15:55:31.570 I/.courville.nov(14532):
06-08 15:55:31.571 W/System.err(14532): OAuthProblemException{error='unsupported_response_type', description='Invalid response! Response body is not application/json encoded', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.response.OAuthJSONAccessTokenResponse.setBody(SourceFile:70)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(SourceFile:56)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(SourceFile:52)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(SourceFile:60)
06-08 15:55:31.571 W/System.err(14532):         at com.uwetrottmann.trakt.v2.TraktHttpClient.execute(SourceFile:73)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.OAuthClient.accessToken(SourceFile:65)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.OAuthClient.accessToken(SourceFile:55)
06-08 15:55:31.571 W/System.err(14532):         at org.apache.oltu.oauth2.client.OAuthClient.accessToken(SourceFile:71)
06-08 15:55:31.571 W/System.err(14532):         at com.uwetrottmann.trakt.v2.TraktV2.getAccessToken(SourceFile:162)
06-08 15:55:31.571 W/System.err(14532):         at com.archos.mediacenter.utils.trakt.Trakt.getAccessToken(SourceFile:264)
06-08 15:55:31.571 W/System.err(14532):         at com.archos.mediacenter.video.utils.TraktSigninDialogPreference$1$1.doInBackground(SourceFile:80)
06-08 15:55:31.571 W/System.err(14532):         at android.os.AsyncTask$2.call(AsyncTask.java:333)
06-08 15:55:31.571 W/System.err(14532):         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-08 15:55:31.571 W/System.err(14532):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
06-08 15:55:31.571 W/System.err(14532):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-08 15:55:31.571 W/System.err(14532):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-08 15:55:31.571 W/System.err(14532):         at java.lang.Thread.run(Thread.java:764)
```

**Comment by courville** [comment]
This is indeed a regression version 3.6 ok and 3.7 ko https://github.com/nova-video-player/aos-AVP/releases i.e. since April 27th.

**Comment by courville** [comment]
Issue comes from new R8 shrinker. Disable it for now.
