### ISSUE TITLE
Crashing Everytime I Open it

### ISSUE THREAD

**Issue by Raul1198** [nova-video-player/aos-AVP#169]
https://del.dog/uviqedukex

**Comment by courville** [comment]
Thank you for sharing the log: it seems that the problem comes from DeleteOnDowngradeSQLiteOpenHelper which would indicate a downgrade of version (uncommon).
Is this after an update through google play or a clean install?
Have you tried 4.x versions on github?
Is this on AndroidTV or phone/tablet?

**Comment by Raul1198** [comment]
I did a clean install from play store, then after as it was crashing I choose to install it from GitHub 4.6 and that too was crashing. Device - Poco f1

**Comment by courville** [comment]
Could you please try to deinstall the 4.6 version and then reinstall from Google Play?
I just did it to check and on my phone it works.
I will nevertheless check this vob_insert_import later today in the code.

**Comment by Raul1198** [comment]
Even after reinstalling same https://del.dog/uruyukevak

**Comment by courville** [comment]
Adding the logcat trace:
```
msg: android.database.sqlite.SQLiteException: error in trigger vob_insert_import: no such table: main.vob_insert (code 1 SQLITE_ERROR)
stacktrace: android.database.sqlite.SQLiteException: error in trigger vob_insert_import: no such table: main.vob_insert (code 1 SQLITE_ERROR)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:786)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1781)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1708)
	at com.archos.mediaprovider.SQLiteUtils.alterTable(SQLiteUtils.java:44)
	at com.archos.mediaprovider.video.VideoOpenHelper.onUpgrade(VideoOpenHelper.java:2615)
	at com.archos.mediaprovider.video.VideoOpenHelper.onCreate(VideoOpenHelper.java:2540)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at com.archos.mediaprovider.DeleteOnDowngradeSQLiteOpenHelper.getWritableDatabase(DeleteOnDowngradeSQLiteOpenHelper.java:48)
	at com.archos.mediaprovider.DbHolder.get(DbHolder.java:47)
	at com.archos.mediaprovider.video.VideoProvider.query(VideoProvider.java:222)
	at android.content.ContentProvider.query(ContentProvider.java:1059)
	at android.content.ContentProvider.query(ContentProvider.java:1151)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
	at android.content.ContentResolver.query(ContentResolver.java:812)
	at android.content.ContentResolver.query(ContentResolver.java:761)
	at android.content.ContentResolver.query(ContentResolver.java:719)
	at com.archos.mediaprovider.video.RemoteStateService.handleDb(RemoteStateService.java:102)
	at com.archos.mediaprovider.video.RemoteStateService.onHandleIntent(RemoteStateService.java:81)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by courville** [comment]
Another report of this issue by mail on t-mobile moto z2 force under Android 9 lineage OS ROM:
```
E/.courville.nov(22278): Not starting debugger since process cannot load the jdwp agent.
E/SQLiteLog(22278): (1) statement aborts at 24: [ALTER TABLE files RENAME TO files__tmp] error in trigger vob_insert_import: no such table: main.vob_insert
E/AndroidRuntime(22278): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(22278): Process: org.courville.nova, PID: 22278
E/AndroidRuntime(22278): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(22278): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime(22278): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(22278): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(22278): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(22278): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22278): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22278): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(22278): Caused by: android.database.sqlite.SQLiteException: error in trigger vob_insert_import: no such table: main.vob_insert (code 1 SQLITE_ERROR)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:786)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1780)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1707)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.SQLiteUtils.alterTable(SQLiteUtils.java:44)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.video.VideoOpenHelper.onUpgrade(VideoOpenHelper.java:2615)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.video.VideoOpenHelper.onCreate(VideoOpenHelper.java:2540)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
E/AndroidRuntime(22278): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.DeleteOnDowngradeSQLiteOpenHelper.getWritableDatabase(DeleteOnDowngradeSQLiteOpenHelper.java:48)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.DbHolder.get(DbHolder.java:47)
E/AndroidRuntime(22278): 	at com.archos.mediaprovider.video.VideoProvider.query(VideoProvider.java:222)
E/AndroidRuntime(22278): 	at android.content.ContentProvider.query(ContentProvider.java:1058)
E/AndroidRuntime(22278): 	at android.content.ContentProvider.query(ContentProvider.java:1150)
E/AndroidRuntime(22278): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
E/AndroidRuntime(22278): 	at android.content.ContentResolver.query(ContentResolver.java:803)
E/AndroidRuntime(22278): 	at android.content.ContentResolver.query(ContentResolver.java:753)
E/AndroidRuntime(22278): 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:68)
E/AndroidRuntime(22278): 	at android.content.CursorLoader.loadInBackground(CursorLoader.java:45)
E/AndroidRuntime(22278): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:319)
E/AndroidRuntime(22278): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:73)
E/AndroidRuntime(22278): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:61)
E/AndroidRuntime(22278): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(22278): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(22278): 	... 3 more
```

**Comment by courville** [comment]
> Another report of this issue by mail on t-mobile moto z2 force under Android 9 lineage OS ROM:

note that the user reinstalled an earlier version of lineage OS and it works now.

**Comment by courville** [comment]
> Poco f1

@Raul1198 could you please let me know if you are using stock ROM or by any chance a lineageOS ROM?

**Comment by courville** [comment]
I might have found the issue that is causing the crash.
Though many devices are immune, this is indeed a bug.
Since I am not experiencing the issue, it would be nice to get the confirmation trying this test apk: https://drive.google.com/file/d/1fpWBKRlfQN3KxqU7xsHoB4sgsEPH1lRm/view?usp=sharing

**Comment by courville** [comment]
OK first bug treated, next in line:
```
D/AMXVideoOpenHelper(12938): Upgrading Database from 10 to 36
E/SQLiteLog(12938): (1) statement aborts at 24: [ALTER TABLE files_scanned RENAME TO files_scanned__tmp] error in trigger after_insert_files_import: no such table: main.files__tmp
E/AndroidRuntime(12938): FATAL EXCEPTION: IntentService[RemoteStateService]
E/AndroidRuntime(12938): Process: org.courville.nova, PID: 12938
E/AndroidRuntime(12938): android.database.sqlite.SQLiteException: error in trigger after_insert_files_import: no such table: main.files__tmp (code 1 SQLITE_ERROR)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:786)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1780)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1707)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.SQLiteUtils.alterTable(SQLiteUtils.java:44)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.video.VideoOpenHelper.onUpgrade(VideoOpenHelper.java:2639)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.video.VideoOpenHelper.onCreate(VideoOpenHelper.java:2545)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
E/AndroidRuntime(12938):        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.DeleteOnDowngradeSQLiteOpenHelper.getWritableDatabase(DeleteOnDowngradeSQLiteOpenHelper.java:48)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.DbHolder.get(DbHolder.java:47)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.video.VideoProvider.query(VideoProvider.java:222)
E/AndroidRuntime(12938):        at android.content.ContentProvider.query(ContentProvider.java:1058)
E/AndroidRuntime(12938):        at android.content.ContentProvider.query(ContentProvider.java:1150)
E/AndroidRuntime(12938):        at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
E/AndroidRuntime(12938):        at android.content.ContentResolver.query(ContentResolver.java:803)
E/AndroidRuntime(12938):        at android.content.ContentResolver.query(ContentResolver.java:753)
E/AndroidRuntime(12938):        at android.content.ContentResolver.query(ContentResolver.java:711)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.video.RemoteStateService.handleDb(RemoteStateService.java:102)
E/AndroidRuntime(12938):        at com.archos.mediaprovider.video.RemoteStateService.onHandleIntent(RemoteStateService.java:81)
E/AndroidRuntime(12938):        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
E/AndroidRuntime(12938):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(12938):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12938):        at android.os.HandlerThread.run(HandlerThread.java:65)
D/AMXVideoOpenHelper(12938): Creating Database at version 10
```

**Comment by deepu2** [comment]
https://pastebin.com/4vTfNxUw

I'm facing this issue too, I've tried play store version, play store beta version and the apk you linked above. 
This log is from the version you linked above.
Sorry if this log is incorrect.
I'm using a custom ROM: cRdroid Pie

**Comment by courville** [comment]
> https://pastebin.com/4vTfNxUw
> 
> I'm facing this issue too, I've tried play store version, play store beta version and the apk you linked above.
> This log is from the version you linked above.
> Sorry if this log is incorrect.
> I'm using a custom ROM: cRdroid Pie

ok thanks for the testing.
If you are still in the mood of helping in the blind bug hunting, please find a new test apk that might improve the situation: https://drive.google.com/open?id=1sWT8odi8w7qyaNBvfgyqj4VdlNJZD4Gh

**Comment by deepu2** [comment]
> > https://pastebin.com/4vTfNxUw
> > I'm facing this issue too, I've tried play store version, play store beta version and the apk you linked above.
> > This log is from the version you linked above.
> > Sorry if this log is incorrect.
> > I'm using a custom ROM: cRdroid Pie
> 
> ok thanks for the testing.
> If you are still in the mood of helping in the blind bug hunting, please find a new test apk that might improve the situation: https://drive.google.com/open?id=1sWT8odi8w7qyaNBvfgyqj4VdlNJZD4Gh

Ah it's working now

**Comment by courville** [comment]
> Ah it's working now

Thanks for the positive feedback and test!
