### ISSUE TITLE
cast crashes on Android P

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#17]
`
09-25 15:25:49.308 I/ActivityManager( 1161): Start proc 2033:org.courville.nova/u0a265 for service org.courville.nova/com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService
09-25 15:25:49.329 E/.courville.nov( 2033): Not starting debugger since process cannot load the jdwp agent.
09-25 15:25:49.369 I/.courville.nov( 2033): The ClassLoaderContext is a special shared library.
09-25 15:25:49.388 I/MultiDex( 2033): VM with version 2.1.0 has multidex support
09-25 15:25:49.388 I/MultiDex( 2033): Installing application
09-25 15:25:49.388 I/MultiDex( 2033): VM has multidex support, MultiDex support library is disabled.
09-25 15:25:49.419 D/NetworkSecurityConfig( 2033): No Network Security Config specified, using platform default
09-25 15:25:49.428 V/LibAvos ( 2033): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/lib/arm, /data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libcryptocompat.so"
09-25 15:25:49.429 V/LibAvos ( 2033): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/lib/arm, /data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libsslcompat.so"
09-25 15:25:49.429 V/LibAvos ( 2033): Can't load library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk"],nativeLibraryDirectories=[/data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/lib/arm, /data/app/org.courville.nova-NmwAH0x3ALVMJJoQDofOMw==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libcurl.so"
09-25 15:25:49.445 V/libavos ( 2033): libavos_acquire
09-25 15:25:49.446 D/avos_player( 2033): libavos_init
09-25 15:25:49.446 D/avos_player( 2033): device_config.has_hdd     0
09-25 15:25:49.446 D/avos_player( 2033): device_config.has_dsp     1
09-25 15:25:49.446 D/avos_player( 2033): device_config.has_dsp_od  1
09-25 15:25:49.446 D/avos_player( 2033): device_config.zone        0
09-25 15:25:49.446 D/avos_player( 2033): device_config.has_archos_enhancement 0
09-25 15:25:49.446 D/avos_player( 2033): device_config.hw_type     unknown
09-25 15:25:49.454 D/SambaConfiguration( 2033): Updating credentials cache
09-25 15:25:49.458 V/libavos ( 2033): libavos_debug_acquire: first init
09-25 15:25:49.459 D/avos_player( 2033): device_config.cpu_count   8
09-25 15:25:49.459 D/avos_player( 2033): dlhelper_dlsym: dlhelper_dlsym failed: undefined symbol: _ZN7android11AudioSystem16getOutputLatencyEPj19audio_stream_type_t
09-25 15:25:49.459 D/avos_player( 2033): dlhelper_as_init: sym_init: dlsym failed: getOutputLatency
09-25 15:25:49.459 D/avos_player( 2033): 
09-25 15:25:49.459 D/avos_player( 2033): audio_interface_init: opensles success
09-25 15:25:49.459 D/avos_player( 2033): creating mainloop (for debug only)
09-25 15:25:49.467 D/ccl_BaseCastManager( 2033): [v2.9.1] BaseCastManager is instantiated
09-25 15:25:49.467 D/ccl_BaseCastManager( 2033): Version: 2.9.1
09-25 15:25:49.467 D/ccl_BaseCastManager( 2033): Application ID: 08FEA4DD
09-25 15:25:49.473 V/MediaRouter( 2033): Adding route: RouteInfo{ name=Téléphone, description=null, status=null, category=RouteCategory{ name=Système types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-25 15:25:49.477 V/MediaRouter( 2033): Selecting route: RouteInfo{ name=Téléphone, description=null, status=null, category=RouteCategory{ name=Système types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-25 15:25:49.480 I/MediaRouter( 2033): Found default route: MediaRouter.RouteInfo{ uniqueId=android/.support.v7.media.SystemMediaRouteProvider:DEFAULT_ROUTE, name=Téléphone, description=null, iconUri=null, enabled=true, connecting=false, connectionState=0, canDisconnect=false, playbackType=0, playbackStream=3, deviceType=0, volumeHandling=1, volume=5, volumeMax=25, presentationDisplayId=-1, extras=null, settingsIntent=null, providerPackageName=android }
09-25 15:25:49.482 D/ccl_VideoCastManager( 2033): [v2.9.1] VideoCastManager is instantiated
09-25 15:25:49.485 D/ccl_VideoCastManager( 2033): [v2.9.1] Successfully added the new MiniController com.archos.mediacenter.video.player.cast.ArchosVideoCastManager@97a05a9
09-25 15:25:49.486 D/ccl_VideoCastManager( 2033): [v2.9.1] Stopped TrickPlay Timer
09-25 15:25:49.486 D/ccl_VideoCastManager( 2033): [v2.9.1] Restarted Progress Timer
09-25 15:25:49.486 D/ccl_BaseCastManager( 2033): [v2.9.1] Successfully added the new BaseCastConsumer listener com.archos.mediacenter.video.player.cast.ArchosVideoCastManager$1@54212cf
09-25 15:25:49.486 D/ccl_VideoCastManager( 2033): [v2.9.1] Successfully added the new CastConsumer listener com.archos.mediacenter.video.player.cast.ArchosVideoCastManager$1@54212cf
09-25 15:25:49.490 D/ccl_BaseCastManager( 2033): [v2.9.1] reconnectSessionIfPossible(10, null)
09-25 15:25:49.490 D/ccl_BaseCastManager( 2033): [v2.9.1] Found session info in the preferences, so proceed with an attempt to reconnect if possible
09-25 15:25:49.490 D/ccl_BaseCastManager( 2033): [v2.9.1] Successfully added the new BaseCastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@39e783a
09-25 15:25:49.490 D/ccl_VideoCastManager( 2033): [v2.9.1] Successfully added the new CastConsumer listener com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$1@39e783a
09-25 15:25:49.490 D/ccl_VideoCastNotificat( 2033): [v2.9.1] onStartCommand
09-25 15:25:49.491 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 1
09-25 15:25:49.492 D/ccl_BaseCastManager( 2033): [v2.9.1] Successfully added the new BaseCastConsumer listener com.archos.mediacenter.video.player.cast.CastService$1@aabc0e1
09-25 15:25:49.492 D/ccl_VideoCastManager( 2033): [v2.9.1] Successfully added the new CastConsumer listener com.archos.mediacenter.video.player.cast.CastService$1@aabc0e1
09-25 15:25:49.492 D/ccl_BaseCastManager( 2033): [v2.9.1] UI is visible
09-25 15:25:49.493 D/CastActivity( 2033): onStartCommand
09-25 15:25:49.495 D/AndroidRuntime( 2033): Shutting down VM
09-25 15:25:49.495 E/AndroidRuntime( 2033): FATAL EXCEPTION: main
09-25 15:25:49.495 E/AndroidRuntime( 2033): Process: org.courville.nova, PID: 2033
09-25 15:25:49.495 E/AndroidRuntime( 2033): java.lang.RuntimeException: Unable to start service com.archos.mediacenter.video.player.cast.CastService@eebde06 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getType()' on a null object reference
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.app.ActivityThread.access$1600(ActivityThread.java:199)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.os.Looper.loop(Looper.java:193)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at java.lang.reflect.Method.invoke(Native Method)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
09-25 15:25:49.495 E/AndroidRuntime( 2033): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getType()' on a null object reference
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at com.archos.mediacenter.video.player.cast.CastService.onStartCommand(CastService.java:304)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3667)
09-25 15:25:49.495 E/AndroidRuntime( 2033): 	... 8 more
09-25 15:25:49.499 I/ActivityManager( 1161): Showing crash dialog for package org.courville.nova u0
09-25 15:25:50.533 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 2
09-25 15:25:51.540 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 3
09-25 15:25:52.583 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 4
09-25 15:25:53.614 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 5
09-25 15:25:54.641 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 6
09-25 15:25:55.667 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 7
09-25 15:25:56.708 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 8
09-25 15:25:57.722 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 9
09-25 15:25:58.724 D/ccl_BaseCastManager( 2033): [v2.9.1] Reconnection: Attempt 10
09-25 15:26:00.492 I/ActivityManager( 1161): Process org.courville.nova (pid 2033) has died: prcp FGS 
09-25 15:26:00.492 W/ActivityManager( 1161): Scheduling restart of crashed service org.courville.nova/com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService in 1800000ms
09-25 15:26:00.492 W/libprocessgroup( 1161): kill(-2033, 9) failed: No such process
09-25 15:26:00.492 W/ActivityManager( 1161): Scheduling restart of crashed service org.courville.nova/com.archos.mediacenter.video.browser.TorrentObserverService in 1810000ms
09-25 15:26:00.493 I/libprocessgroup( 1161): Successfully killed process cgroup uid 10265 pid 2033 in 0ms
09-25 15:26:00.493 W/ActivityManager( 1161): Scheduling restart of crashed service org.courville.nova/com.archos.mediacenter.video.player.cast.CastService in 1820000ms
`

**Comment by courville** [comment]
Easy fix: remove cast...

**Comment by courville** [comment]
Closes #17 via https://github.com/nova-video-player/aos-Video/commit/30fb059fcffa3ab6dfb96d6cf8bad6b53b8aca96
