### ISSUE TITLE
trakt seen import sync is failing

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#184]
Reported on reddit: https://www.reddit.com/r/NovaVideoPlayer/comments/cm758n/anyone_else_having_issues_with_trakt/
From device to trakt it works.
Quick logcat (perhaps unrelated) gives:
```
08-18 23:03:11.415  6839  7149 W System.err: retrofit.RetrofitError: 502 Bad Gateway
08-18 23:03:11.417  6839  7149 W System.err:    at retrofit.RestAdapter$RestHandler.invokeRequest(SourceFile:388)
08-18 23:03:11.417  6839  7149 W System.err:    at retrofit.RestAdapter$RestHandler.invoke(SourceFile:240)
08-18 23:03:11.417  6839  7149 W System.err:    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
08-18 23:03:11.417  6839  7149 W System.err:    at $Proxy7.settings(Unknown Source)
08-18 23:03:11.417  6839  7149 W System.err:    at com.archos.mediacenter.utils.trakt.Trakt.getListContent(SourceFile:794)
08-18 23:03:11.417  6839  7149 W System.err:    at com.archos.mediacenter.utils.trakt.TraktService.syncLists(SourceFile:1097)
08-18 23:03:11.418  6839  7149 W System.err:    at com.archos.mediacenter.utils.trakt.TraktService.sync(SourceFile:941)
08-18 23:03:11.418  6839  7149 W System.err:    at com.archos.mediacenter.utils.trakt.TraktService.access$500(SourceFile:71)
08-18 23:03:11.418  6839  7149 W System.err:    at com.archos.mediacenter.utils.trakt.TraktService$TraktHandler.handleMessage(SourceFile:266)
08-18 23:03:11.418  6839  7149 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
08-18 23:03:11.418  6839  7149 W System.err:    at android.os.Looper.loop(Looper.java:193)
08-18 23:03:11.418  6839  7149 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by courville** [comment]
Wild guess it is due to api evolution and https://github.com/nova-video-player/aos-AVP/issues/116

**Comment by courville** [comment]
MediaLib and Video trakt-java current branch seems to fix the issue. But aligning on external lib requires to upstream scrobbling.
