### ISSUE TITLE
buildAllMoviesBox and  buildAllTvshowsBox creating on db main thread error message

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#204]
Async task needed
```
2019-09-28 00:03:35.733 7546-7546/org.courville.nova W/AMXDbHolder: java.lang.Exception: CREATING DATABASE ON MAIN THREAD
        at com.archos.mediaprovider.DbHolder.logUiThread(DbHolder.java:59)
        at com.archos.mediaprovider.DbHolder.get(DbHolder.java:41)
        at com.archos.mediaprovider.video.VideoProvider.query(VideoProvider.java:227)
        at android.content.ContentProvider.query(ContentProvider.java:1147)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:240)
        at android.content.ContentResolver.query(ContentResolver.java:754)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.archos.mediacenter.video.leanback.movies.AllMoviesIconBuilder.getPostersList(AllMoviesIconBuilder.java:95)
        at com.archos.mediacenter.video.leanback.movies.AllMoviesIconBuilder.buildIconBitmap(AllMoviesIconBuilder.java:84)
        at com.archos.mediacenter.video.leanback.movies.AllMoviesIconBuilder.buildNewBitmap(AllMoviesIconBuilder.java:72)
        at com.archos.mediacenter.video.leanback.MainFragment.buildAllMoviesBox(MainFragment.java:477)
        at com.archos.mediacenter.video.leanback.MainFragment.loadRows(MainFragment.java:419)
        at com.archos.mediacenter.video.leanback.MainFragment.onActivityCreated(MainFragment.java:237)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2619)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
        at android.app.Activity.performStart(Activity.java:7029)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by courville** [comment]
Closing due to inactivity and possibly prior solving. Please reopen an issue if needed.
