### ISSUE TITLE
playconsole: NetworkScannerServiceVideo leaks IntentReceiver

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#207]
```
2019-10-05 23:38:11.230 31911-31911/org.courville.nova E/ActivityThread: Service
                    com.archos.mediaprovider.video.NetworkScannerServiceVideo has leaked IntentReceiver
                    com.archos.mediacenter.filecoreextension.upnp2.UpnpServiceManager@c4adde7 that was originally registered here. Are you missing a call to unregisterReceiver()?
     android.app.IntentReceiverLeaked: Service  com.archos.mediaprovider.video.NetworkScannerServiceVideo has leaked IntentReceiver com.archos.mediacenter.filecoreextension.upnp2.UpnpServiceManager@c4adde7 that was originally registered here. Are you missing a call to unregisterReceiver()? at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
         at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
         at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
         at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
         at com.archos.mediacenter.filecoreextension.upnp2.UpnpServiceManager.startUpnpServiceIfNotStartedYet(UpnpServiceManager.java:147)
         at                 com.archos.mediacenter.filecoreextension.upnp2.UpnpServiceManager.getSingleton(UpnpServiceManager.java:140)
         at com.archos.mediaprovider.video.NetworkScannerServiceVideo.onCreate(NetworkScannerServiceVideo.java:199)
         at android.app.ActivityThread.handleCreateService(ActivityThread.java:
```

**Comment by courville** [comment]
Seppel comment: that's probably because NetworkscannerServiceVideo uses "UpnpServiceManager.getSingleton(this)" and UpnpServiceManager then registering itself as broadcastreceiver using the service/this as context which outlives the service. This error might go away if you change the code in such a way that the receiver is created with application context.
