### ISSUE TITLE
phones: refresh all videos after file delete

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#213]
For now deleted files remain in the list until application is relaunched.

**Comment by courville** [comment]
This is a regression compared to 4.15

**Comment by courville** [comment]
```
2019-11-04 13:53:55.371 17993-18116/org.courville.nova W/MessageQueue: Handler (android.os.Handler) {1fcf319} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {1fcf319} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at android.database.ContentObserver.dispatchChange(ContentObserver.java:200)
        at android.database.ContentObserver.access$000(ContentObserver.java:28)
        at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
        at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:98)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2019-11-04 13:53:55.371 17993-18102/org.courville.nova W/MessageQueue: Handler (android.os.Handler) {37c8260} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {37c8260} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at android.database.ContentObserver.dispatchChange(ContentObserver.java:200)
        at android.database.ContentObserver.access$000(ContentObserver.java:28)
        at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
        at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:98)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2019-11-04 13:53:55.372 17993-18102/org.courville.nova W/MessageQueue: Handler (android.os.Handler) {37c8260} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {37c8260} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at android.database.ContentObserver.dispatchChange(ContentObserver.java:200)
        at android.database.ContentObserver.access$000(ContentObserver.java:28)
        at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
        at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:98)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2019-11-04 13:53:55.372 17993-18116/org.courville.nova W/MessageQueue: Handler (android.os.Handler) {1fcf319} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {1fcf319} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
        at android.os.Handler.enqueueMessage(Handler.java:754)
        at android.os.Handler.sendMessageAtTime(Handler.java:703)
        at android.os.Handler.sendMessageDelayed(Handler.java:673)
        at android.os.Handler.post(Handler.java:403)
        at android.database.ContentObserver.dispatchChange(ContentObserver.java:200)
        at android.database.ContentObserver.access$000(ContentObserver.java:28)
        at android.database.ContentObserver$Transport.onChange(ContentObserver.java:233)
        at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:98)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by courville** [comment]
When going all videos, delete, then go in all series, then all videos:
```
2019-11-04 13:58:41.119 17993-17993/org.courville.nova D/Browser: bindAdapter: true
2019-11-04 13:58:49.552 17993-17993/org.courville.nova D/Browser: bindAdapter: true
2019-11-04 13:58:49.680 17993-18008/org.courville.nova D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at android.content.ContentResolver$CursorWrapperInner.finalize(ContentResolver.java:3347)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at android.content.ContentResolver$CursorWrapperInner.<init>(ContentResolver.java:3330)
        at android.content.ContentResolver.query(ContentResolver.java:970)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.archos.mediacenter.video.browser.Delete.getAssociatedFiles(Delete.java:383)
        at com.archos.mediacenter.video.browser.Delete.deleteFileAndAssociatedFiles(Delete.java:246)
        at com.archos.mediacenter.video.browser.Delete$3.run(Delete.java:190)
```
