### ISSUE TITLE
upgrade jcsh

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#223]
Original version is based on 0.1.51 (verified) and latest version is 0.1.55.
Note that the following patches have been applied on top of 0.1.51 compared to original import: [jcsh-0.1.51-parches.zip](https://github.com/nova-video-player/aos-AVP/files/3816955/jcsh-0.1.51-parches.zip)
https://github.com/nova-video-player/aos-FileCoreLibrary/commit/9ed23644a11d6a32c7dd50f5d6c7845443c9b0fd is a manual upgrade adding missing files.
It compiles but when playing content app crashes after a while:
```
019-11-06 23:04:13.920 29518-29677/org.courville.nova W/.courville.nov: Long monitor contention with owner Thread-32 (29682) at com.jcraft.jsch.Channel com.archos.filecorelibrary.sftp.SFTPSession.getSFTPChannel(android.net.Uri)(SFTPSession.java:-1) waiters=0 in void com.archos.filecorelibrary.sftp.SFTPSession.releaseSession(com.jcraft.jsch.Channel) for 950ms
2019-11-06 23:04:14.551 29518-29677/org.courville.nova W/.courville.nov: Long monitor contention with owner Thread-32 (29682) at com.jcraft.jsch.Channel com.archos.filecorelibrary.sftp.SFTPSession.getSFTPChannel(android.net.Uri)(SFTPSession.java:-1) waiters=0 in void com.archos.filecorelibrary.sftp.SFTPSession.releaseSession(com.jcraft.jsch.Channel) for 350ms
2019-11-06 23:04:14.753 29518-29518/org.courville.nova I/Choreographer: Skipped 54 frames!  The application may be doing too much work on its main thread.
2019-11-06 23:04:15.165 29518-29682/org.courville.nova E/AndroidRuntime: FATAL EXCEPTION: Thread-32
    Process: org.courville.nova, PID: 29518
    java.lang.IllegalArgumentException: Requested path /sftp:/home.courville.org:22/volume1/download/transmission/serie-hd/Arrow.S08E01.720p.HDTV.x265-MiNX[eztv].mkv doesn't appear under [/storage/emulated/0]
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
        at android.content.ContentResolver.insert(ContentResolver.java:1828)
        at com.archos.mediaprovider.video.VideoStore.requestIndexing(VideoStore.java:131)
        at com.archos.mediaprovider.video.VideoStore.requestIndexing(VideoStore.java:72)
        at com.archos.mediacenter.video.player.PlayerService$9.run(PlayerService.java:1073)
2019-11-06 23:04:15.178 29518-29518/org.courville.nova D/AVP: Sending paused intent
2019-11-06 23:04:15.181 29518-29682/org.courville.nova I/Process: Sending signal. PID: 29518 SIG: 9
```

**Comment by courville** [comment]
This crash is not linked to the upgrade.
