### ISSUE TITLE
sftp: NoSuchFieldException opening shares

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#227]
When opening sftp share we get the following:
```
2019-11-07 09:27:37.346 26141-26311/org.courville.nova D/JSCH: Couldn't get target
    java.lang.NoSuchFieldException: No field target in class Ljava/io/PipedOutputStream; (declaration of 'java.io.PipedOutputStream' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.jcraft.jsch.Channel.targetFromPiped(Channel.java:333)
        at com.jcraft.jsch.Channel.<clinit>(Channel.java:341)
        at com.jcraft.jsch.Channel.getChannel(Channel.java:56)
        at com.jcraft.jsch.Session.openChannel(Session.java:847)
        at com.archos.filecorelibrary.sftp.SFTPSession.getSFTPChannel(SFTPSession.java:51)
        at com.archos.filecorelibrary.sftp.SFtpListingEngine$SFtpListingThread.run(SFtpListingEngine.java:108)
```

**Comment by courville** [comment]
Closing due to inactivity and possibly prior solving. Please reopen an issue if needed.
