### ISSUE TITLE
v4.16 google play console: NullPointerException in ManualShowScrappingSearchFragment$EpSaveTask.getEpisode

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#235]
```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:354)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.NullPointerException: 
  at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.getEpisode (ManualShowScrappingSearchFragment.java:379)
  at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.handleSave (ManualShowScrappingSearchFragment.java:321)
  at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.doInBackground (ManualShowScrappingSearchFragment.java:215)
  at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.doInBackground (ManualShowScrappingSearchFragment.java:178)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by courville** [comment]
Crash can be reproduced when on leanback changing the information of the whole tv show and selecting a wrong one leading to showdetails nok. In getEpisode map is thus null because not set in handleSave since ! detail.isOkay()

```
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | FATAL EXCEPTION: AsyncTask #101
-- | -- | -- | -- | --
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | Process: org.courville.nova, PID: 12393
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | java.lang.RuntimeException: An error occurred while executing doInBackground()
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at android.os.AsyncTask$3.done(AsyncTask.java:353)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.lang.Thread.run(Thread.java:764)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.getEpisode(SourceFile:383)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.handleSave(SourceFile:324)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.doInBackground(SourceFile:215)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at com.archos.mediacenter.video.leanback.scrapping.ManualShowScrappingSearchFragment$EpSaveTask.doInBackground(SourceFile:178)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at android.os.AsyncTask$2.call(AsyncTask.java:333)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-27 20:25:59.392 | E | AndroidRuntime | 12393 | ... 4 more
```
