### ISSUE TITLE
leanback VideoDetailFragment delete file on sdcard for Sony does not work

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#242]
```
11-18 18:58:49.081 22919 23521 E MediaProvider: Couldn't delete /storage/F9E6-A225/mininas/serie/blah.mkv
11-18 18:51:25.142  9079 24640 E Delete  : com.archos.filecorelibrary.localstorage.LocalStorageFileEditor$DeleteFailException
11-18 18:51:25.142  9079 24640 E Delete  :      at com.archos.filecorelibrary.localstorage.LocalStorageFileEditor.deleteFileAndDatabase(SourceFile:233)
11-18 18:51:25.142  9079 24640 E Delete  :      at com.archos.mediacenter.video.browser.Delete.deleteFileAndAssociatedFiles(SourceFile:257)
11-18 18:51:25.142  9079 24640 E Delete  :      at com.archos.mediacenter.video.browser.Delete$3.run(SourceFile:190)
11-18 18:58:49.095  9079 24477 W MessageQueue: Handler (android.os.Handler) {4ffa467} sending message to a Handler on a dead thread
11-18 18:58:49.095  9079 24477 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {4ffa467} sending message to a Handler on a dead thread
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.Handler.post(Handler.java:356)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.database.ContentObserver.dispatchChange(ContentObserver.java:198)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.database.ContentObserver.-wrap0(Unknown Source:0)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.database.ContentObserver$Transport.onChange(ContentObserver.java:231)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.database.IContentObserver$Stub.onTransact(IContentObserver.java:62)
11-18 18:58:49.095  9079 24477 W MessageQueue: 	at android.os.Binder.execTransact(Binder.java:674)
```

**Comment by courville** [comment]
Duplicate https://github.com/nova-video-player/aos-AVP/issues/244
