### ISSUE TITLE
shield external drive scraping error

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#243]
```
11-18 20:33:24.362  9463 10174 E ShowScraper2: getDetailsInternal
11-18 20:33:24.362  9463 10174 E ShowScraper2: java.lang.NumberFormatException: For input string: "graphical"
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at java.lang.Integer.parseInt(Integer.java:615)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at java.lang.Integer.parseInt(Integer.java:650)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.ShowScraper2.getDetailsInternal(SourceFile:435)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.BaseScraper2.getDetails(SourceFile:143)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.BaseScraper2.search(SourceFile:105)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.Scraper.getAutoDetails(SourceFile:103)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.AutoScrapeService$3.run(SourceFile:417)
```

**Comment by courville** [comment]
Happens when thetvdb is fubar

**Comment by courville** [comment]
Duplicate https://github.com/nova-video-player/aos-AVP/issues/245
