### ISSUE TITLE
external storage management should use Storage Framework Access

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#244]
Deleting files on external sdcard or usb drive fails:
```
2019-11-18 21:42:31.427 5558-6516/org.courville.nova E/Delete: Failed to delete file file:///storage/1C07-0914/toto.nfo
    com.archos.filecorelibrary.localstorage.LocalStorageFileEditor$DeleteFailException
        at com.archos.filecorelibrary.localstorage.LocalStorageFileEditor.deleteFileAndDatabase(LocalStorageFileEditor.java:233)
        at com.archos.mediacenter.video.browser.Delete.deleteFileAndAssociatedFiles(Delete.java:257)
        at com.archos.mediacenter.video.browser.Delete$3.run(Delete.java:190)
2019-11-18 21:42:31.432 5558-6516/org.courville.nova W/System.err: java.lang.IllegalArgumentException: MIME type text/plain cannot be inserted into content://media/external/images/media; expected MIME type under image/*
2019-11-18 21:42:31.432 5558-6516/org.courville.nova W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
2019-11-18 21:42:31.432 5558-6516/org.courville.nova W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at android.content.ContentResolver.insert(ContentResolver.java:1828)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.filecorelibrary.localstorage.ExternalSDFileWriter.delete(ExternalSDFileWriter.java:85)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.filecorelibrary.localstorage.LocalStorageFileEditor.deleteFile(LocalStorageFileEditor.java:184)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.filecorelibrary.localstorage.LocalStorageFileEditor.delete(LocalStorageFileEditor.java:166)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.mediacenter.video.browser.subtitlesmanager.SubtitleManager.deleteAssociatedSubs(SubtitleManager.java:97)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.mediacenter.video.browser.Delete.deleteFileAndAssociatedFiles(Delete.java:270)
2019-11-18 21:42:31.433 5558-6516/org.courville.nova W/System.err:     at com.archos.mediacenter.video.browser.Delete$3.run(Delete.java:190)
```

**Comment by courville** [comment]
Suppressing files on  usb disks on Android 9 on shield or Android 8 on Sony TV does not work even with FAT32 filesystem.
Suppressing files on Android 9 phones (Samsung S8) is ok.
Listing files on usb disk on Android 10 pixel3xl is KO.
Must be a new Android 10 behavior.

**Comment by courville** [comment]
On Sony TV:
```
2019-11-19 08:43:13.701 7203-7498/? E/Delete: Failed to delete file file:///storage/F9E6-A225/mininas/toto.avi
    com.archos.filecorelibrary.localstorage.LocalStorageFileEditor$DeleteFailException
        at com.archos.filecorelibrary.localstorage.LocalStorageFileEditor.deleteFileAndDatabase(SourceFile:233)
        at com.archos.mediacenter.video.browser.Delete.deleteFileAndAssociatedFiles(SourceFile:257)
        at com.archos.mediacenter.video.browser.Delete$3.run(SourceFile:190)
```

**Comment by courville** [comment]
On first report note the tripe / : file:///storage/1C07-0914/toto.nfo

**Comment by courville** [comment]
This is simple https://stackoverflow.com/questions/40068984/universal-way-to-write-to-external-sd-card-on-android/40201333#40201333

**Comment by courville** [comment]
For now no resume or scape adjustments on external hdd/usb key.
Seems that sdcard ok.

**Comment by courville** [comment]
On pixel3xl android 10 after going to sdcard on nova I get an endless spinning progress dialog
```
11-20 16:37:06.060  3202  3404 D TraktService: syncLists
11-20 16:37:06.761  3202  3461 D LocalStorageListingEngine: listing files for /mnt/media_rw/F9E6-A225
11-20 16:37:06.763  3202  3463 D ContentProviderListingEngine: listing files for content://com.android.externalstorage.documents/tree/F9E6-A225%3A
11-20 16:37:06.763  3202  3463 D ContentProviderListingEngine: listing files for1 content://com.android.externalstorage.documents/tree/F9E6-A225%3A
11-20 16:37:06.764  3202  3463 W System.err: java.lang.ClassNotFoundException: android.support.v4.provider.TreeDocumentFile
11-20 16:37:06.765  3202  3463 W System.err: 	at java.lang.Class.classForName(Native Method)
11-20 16:37:06.765  3202  3463 W System.err: 	at java.lang.Class.forName(Class.java:454)
11-20 16:37:06.765  3202  3463 W System.err: 	at java.lang.Class.forName(Class.java:379)
11-20 16:37:06.765  3202  3463 W System.err: 	at com.archos.filecorelibrary.contentstorage.DocumentUriBuilder.getDocumentFileForUri(SourceFile:104)
11-20 16:37:06.765  3202  3463 W System.err: 	at com.archos.filecorelibrary.contentstorage.ContentProviderListingEngine$ListingThread.run(SourceFile:82)
11-20 16:37:06.765  3202  3463 W System.err: Caused by: java.lang.ClassNotFoundException: android.support.v4.provider.TreeDocumentFile
11-20 16:37:06.765  3202  3463 W System.err: 	... 5 more
```
