### ISSUE TITLE
tvshow scrape issue following 19/11/16 thetvdb site changes

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#245]
NVP was crashing with old API, released v4.16 with thetvdb-java APIv2 move.
During scraping experienced these:
```
11-18 20:33:24.362  9463 10174 E ShowScraper2: getDetailsInternal
11-18 20:33:24.362  9463 10174 E ShowScraper2: java.lang.NumberFormatException: For input string: "graphical"
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at java.lang.Integer.parseInt(Integer.java:615)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at java.lang.Integer.parseInt(Integer.java:650)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.ShowScraper2.getDetailsInternal(SourceFile:435)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.BaseScraper2.getDetails(SourceFile:143)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.xml.BaseScraper2.search(SourceFile:105)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.Scraper.getAutoDetails(SourceFile:103)
11-18 20:33:24.362  9463 10174 E ShowScraper2: 	at com.archos.mediascraper.AutoScrapeService$3.run(SourceFile:417)
```
However the season set to "graphical" is not reproduced on thetvdb swagger https://api.thetvdb.com/swagger#!/Series/get_series_id_images for the specific id causing this error.
This results in NVP not finding any image (might be a thetvdb-java issue).

**Comment by courville** [comment]
Cf. https://forums.thetvdb.com/viewforum.php?f=122&sid=638d64ab177562e5bc7a7ee731f346b6

**Comment by courville** [comment]
TODO: investigate why all tv seasons have same poster.

**Comment by courville** [comment]
Cloud response is unstable: https://forums.thetvdb.com/viewtopic.php?f=122&t=60290
on multiple devices I get strange answers that are not uniform from time to time:

`curl -X GET --header 'Accept: application/vnd.thetvdb.v2.2.0' --header 'Accept: application/json' --header 'Accept-Language: en' --header 'Authorization: Bearer BLAH-TOP-SECRET' 'https://api.thetvdb.com/series/78804/im ... ype=season' | cut -c 1-200
`
Sometimes I get for subKey the correct season number

`{"data":[{"id":61450072,"keyType":"season","subKey":"0","fileName":"seasons/78804-0-2.jpg","languageId":7,"language":"en","resolution":"680x1000","ratingsInfo":{"average":0,"count":0},"thumbnail":"sea`

but sometimes I get subKey "graphical"

`{"data":[{"id":61450072,"keyType":"season","subKey":"graphical","fileName":"seasons/78804-0-2.jpg","languageId":7,"language":"en","resolution":"680x1000","ratingsInfo":{"average":0,"count":0},"thumbnail":"sea`

Since nova is expecting an integer at this stage it was causing major issues...

I would say that you have still some instances running strange...

**Comment by courville** [comment]
Some scraper logs: 
[scraper.log.zip](https://github.com/nova-video-player/aos-AVP/files/3933431/scraper.log.zip)

**Comment by courville** [comment]
tvshows order is not good anymore (not sorted based on popularity). Trying to remove first tvshows without posters cf. https://github.com/nova-video-player/aos-MediaLib/commit/e46786669608b9ea858bfe6791fce7c23c0f21c8 and  https://github.com/nova-video-player/aos-MediaLib/commit/cc277527833fb5e846d41860795ac7861d73632a
Then deprioritize the shows with numeric only slug https://github.com/nova-video-player/aos-MediaLib/commit/7f64d00d657016488e8186e0fc1755babb8b9620

**Comment by courville** [comment]
Above solves Silicon Valley and The good place.
Still some issues reported with Hanna.S01E01.Forest.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG[eztv].mkv, Comedians.In.Cars.Getting.Coffee.S01E01.720p.WEB-DL.H.264.AAC2.0.mp4,  White.Collar.S01E01.Pilot.720p.Web-DL.ReEnc-DeeJayAhmed.mkv
For these ones on White Collar there is an empty poster and it should not with:
```
2019-12-11 23:02:54.647 7806-8074/org.courville.nova E/ShowScraper2: getDetailsInternal
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.archos.mediascraper.ScraperImage.asList()' on a null object reference
        at com.archos.mediascraper.xml.ShowScraper2.getDetailsInternal(ShowScraper2.java:506)
        at com.archos.mediascraper.xml.BaseScraper2.getDetails(BaseScraper2.java:143)
        at com.archos.mediascraper.Scraper.getDetails(Scraper.java:86)
        at com.archos.mediacenter.video.info.VideoInfoScraperSearchFragment$ScraperSelectionThread.run(VideoInfoScraperSearchFragment.java:570)
2019-12-11 23:02:55.120 7806-8074/org.courville.nova D/ScraperImage: mThumbFile = /storage/emulated/0/Android/data/org.courville.nova/files/backdrops/-1937312772-322183440t.jpg
2019-12-11 23:02:55.121 7806-8074/org.courville.nova D/ScraperImage: mLargeFile = /storage/emulated/0/Android/data/org.courville.nova/files/backdrops/-1937312772154621819l.jpg
2019-12-11 23:02:55.536 7806-8074/org.courville.nova E/ShowScraper2: getDetailsInternal
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.archos.mediascraper.ScraperImage.asList()' on a null object reference
        at com.archos.mediascraper.xml.ShowScraper2.getDetailsInternal(ShowScraper2.java:506)
        at com.archos.mediascraper.xml.BaseScraper2.getDetails(BaseScraper2.java:143)
        at com.archos.mediascraper.Scraper.getDetails(Scraper.java:86)
        at com.archos.mediacenter.video.info.VideoInfoScraperSearchFragment$ScraperSelectionThread.run(VideoInfoScraperSearchFragment.java:570)
```

**Comment by courville** [comment]
Some notes on scrape process: https://github.com/nova-video-player/aos-AVP/wiki/Scrape:-retrieve-video-meta-data

**Comment by courville** [comment]
Add Levenshtein distance computation to sort probable results only: https://github.com/nova-video-player/aos-MediaLib/commit/e182d24e282eb6b0b64fb05f4ea617338a9cd07b

**Comment by courville** [comment]
Avoid code duplication https://github.com/nova-video-player/aos-MediaLib/commit/9cbf8cf868ac0c5925fcdc635beac4635221506a

**Comment by courville** [comment]
See https://gitlab.thetvdb.com/site/thetvdb_api/issues/75
