### ISSUE TITLE
TraktService: IllegalStateException  Not allowed to start service Intent 

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#251]
```
java.lang.IllegalStateException: Not allowed to start service Intent { act=archos.mediacenter.utils.trakt.action.SYNC cmp=org.courville.nova/com.archos.mediacenter.utils.trakt.TraktService (has extras) }: app is in background uid UidRecord{61a28e7 u0a300 TPSL bg:+36m55s327ms idle change:cached procs:1 proclist:31510, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1666)
	at android.app.ContextImpl.startService(ContextImpl.java:1611)
	at android.content.ContextWrapper.startService(ContextWrapper.java:677)
	at com.archos.mediacenter.utils.trakt.TraktService$Client.sync(SourceFile:1384)
	at com.archos.mediacenter.utils.trakt.TraktService.sync(SourceFile:1390)
	at com.archos.mediacenter.utils.trakt.TraktService$3.onForeGroundState(SourceFile:1402)
	at com.archos.mediacenter.utils.AppState.notifyListener(SourceFile:76)
	at com.archos.mediacenter.utils.AppState$1.onActivityStarted(SourceFile:112)
	at android.app.Application.dispatchActivityStarted(Application.java:255)
	at android.app.Activity.onStart(Activity.java:1338)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:536)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:201)
	at com.archos.mediacenter.video.player.PlayerActivity.onStart(SourceFile:774)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7348)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3138)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by courville** [comment]
Thanks to seppel explanation.
Crash is triggered by activity.onStart, so shouldn't be considered background unless it's already decided by the system to stop the app again.
See https://stackoverflow.com/questions/52013545/android-9-0-not-allowed-to-start-service-app-is-in-background-after-onresume
The stacktrace says it's happening during the Activity.onStart callback which is the place that is called when you go back to foreground, unless you're on the buggy Pie version of Android where it can apparently happen that the system already decided you need to stay in background and you'll get
the real "onStart" callback at a later point in time.
