### ISSUE TITLE
ScraperProvider: IllegalArgumentException: the bind value at index 1 is null

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#252]
```
java.lang.IllegalArgumentException: the bind value at index 1 is null
	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:399)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
	at com.archos.mediaprovider.video.ScraperProvider.query(SourceFile:928)
	at android.content.ContentProvider.query(ContentProvider.java:1057)
	at com.archos.mediaprovider.video.VideoProvider.query(SourceFile:227)
	at android.content.ContentProvider.query(ContentProvider.java:1149)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
	at android.content.ContentResolver.query(ContentResolver.java:754)
	at android.content.ContentResolver.query(ContentResolver.java:704)
	at android.content.ContentResolver.query(ContentResolver.java:662)
	at com.archos.mediascraper.ShowTags.save(SourceFile:114)
	at com.archos.mediascraper.EpisodeTags.save(SourceFile:120)
	at com.archos.mediascraper.AutoScrapeService$3.run(SourceFile:437)
```

**Comment by courville** [comment]
bindvalue 1 is null and nameseed null would both be the ShowTags mTitle being null, which probably means something with tvdb api still not working as before? e.g. https://github.com/nova-video-player/aos-MediaLib/blob/v4/src/com/archos/mediascraper/xml/ShowScraper2.java#L277 failing and nothing setting the title fallback thing

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-MediaLib/commit/9c44d3a2a7c820d6efdf643bf01aba8d4df54b08
