### ISSUE TITLE
llegalStateException in NetworkRootFragment-not attached to a context in onPostExecute

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#253]
```
java.lang.IllegalStateException: Fragment NetworkRootFragment{ab67765 (15238b8d-2c16-4b94-88f2-5a55894862e5)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(SourceFile:774)
	at androidx.fragment.app.Fragment.getResources(SourceFile:838)
	at androidx.fragment.app.Fragment.getString(SourceFile:860)
	at com.archos.mediacenter.video.leanback.network.NetworkRootFragment$FtpShortcutsLoaderTask.onPostExecute(SourceFile:387)
	at com.archos.mediacenter.video.leanback.network.NetworkRootFragment$FtpShortcutsLoaderTask.onPostExecute(SourceFile:379)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by courville** [comment]
See https://stackoverflow.com/questions/10919240/fragment-myfragment-not-attached-to-activity
