### ISSUE TITLE
v4.37 IllegalArgumentException ggplay console error 

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#312]
Reverted for now the file picker fixes since it was causing massive errors on Google Play console
```
java.lang.IllegalArgumentException: Failed to find configured root that contains /system/media/Pre-loaded/Movies/Touch_The_Sky.mp4
FATAL EXCEPTION: ControllerMessenger
Process: org.courville.nova, PID: 18383
java.lang.IllegalArgumentException: Failed to find configured root that contains /system/media/Pre-loaded/Movies/Touch_The_Sky.mp4
  at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(SourceFile:744)
  at androidx.core.content.FileProvider.getUriForFile(SourceFile:418)
  at com.archos.mediacenter.video.utils.PlayUtils.onResumeReady(SourceFile:245)
  at com.archos.mediacenter.video.utils.PlayUtils.startPlayer(SourceFile:174)
  at com.archos.mediacenter.video.utils.PlayUtils.startVideo(SourceFile:147)
  at com.archos.mediacenter.video.leanback.details.VideoDetailsFragment.startAds(SourceFile:1545)
  at com.archos.mediacenter.video.leanback.details.VideoDetailsFragment.access$1800(SourceFile:146)
  at com.archos.mediacenter.video.leanback.details.VideoDetailsFragment$6.onActionClicked(SourceFile:569)
  at androidx.leanback.widget.FullWidthDetailsOverviewRowPresenter$ActionsItemBridgeAdapter$1.onClick(SourceFile:131)
  at android.view.View.performClick(View.java:4766)
  at android.view.View$PerformClick.run(View.java:19683)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at androidx.test.espresso.base.Interrogator.a(Interrogator.java:20)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:169)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:161)
  at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
  at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:77)
  at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
  at androidx.test.espresso.action.Tap.c(Tap.java:8)
  at androidx.test.espresso.action.Tap.b(Tap.java:19)
  at androidx.test.espresso.action.Tap$1.a(Tap.java:3)
  at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:20)
  at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
  at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
  at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:97)
  at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5538)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-FileCoreLibrary/commit/ca2487c5439a3b01423d532528edd446c00de84f
See https://github.com/nova-video-player/aos-Video/commit/29d89ee13ec89db31a6fbdf740b48f4a97576715
