### ISSUE TITLE
DatagramIO errors with cling

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#321]
Seems that we need to constrain discovery on Wi-Fi to avoid this:
```
03-23 23:28:20.885   323   613 E DatagramIO: Exception sending datagram to: /239.255.255.250: java.io.IOException: sendto failed: EPERM (Operation not permitted)
03-23 23:28:20.885   323   613 E DatagramIO: java.io.IOException: sendto failed: EPERM (Operation not permitted)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:590)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.IoBridge.sendto(IoBridge.java:558)
03-23 23:28:20.885   323   613 E DatagramIO:    at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
03-23 23:28:20.885   323   613 E DatagramIO:    at java.net.DatagramSocket.send(DatagramSocket.java:721)
03-23 23:28:20.885   323   613 E DatagramIO:    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(SourceFile:159)
03-23 23:28:20.885   323   613 E DatagramIO:    at org.fourthline.cling.transport.impl.DatagramIOImpl.send(SourceFile:150)
03-23 23:28:20.885   323   613 E DatagramIO:    at org.fourthline.cling.transport.RouterImpl.send(SourceFile:309)
03-23 23:28:20.885   323   613 E DatagramIO:    at org.fourthline.cling.protocol.async.SendingSearch.execute(SourceFile:91)
03-23 23:28:20.885   323   613 E DatagramIO:    at org.fourthline.cling.protocol.SendingAsync.run(SourceFile:54)
03-23 23:28:20.885   323   613 E DatagramIO:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-23 23:28:20.885   323   613 E DatagramIO:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-23 23:28:20.885   323   613 E DatagramIO:    at java.lang.Thread.run(Thread.java:919)
03-23 23:28:20.885   323   613 E DatagramIO: Caused by: android.system.ErrnoException: sendto failed: EPERM (Operation not permitted)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.Linux.sendtoBytes(Native Method)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.Linux.sendto(Linux.java:233)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.ForwardingOs.sendto(ForwardingOs.java:194)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:366)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.ForwardingOs.sendto(ForwardingOs.java:194)
03-23 23:28:20.885   323   613 E DatagramIO:    at libcore.io.IoBridge.sendto(IoBridge.java:556)
03-23 23:28:20.885   323   613 E DatagramIO:    ... 10 more
```
See https://github.com/4thline/cling/issues/224 and https://github.com/tobexyz/yaacc-code/issues/34

**Comment by courville** [comment]
To fix it, it requires some cling modifications to restrict network to wifi either https://developer.android.com/reference/android/net/ConnectivityManager#bindProcessToNetwork(android.net.Network) for global process but not really possible with whole nova or  on specific socket https://developer.android.com/reference/android/net/Network#bindSocket(java.net.DatagramSocket)

Since cling is EOL will leave with current error.

Limited periodic scan in upnpManager to every 10mn instead of 1mn to decrease verbosity...
