### ISSUE TITLE
StackOverflowError caused by NetworkState propertyChangeListener

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#331]
Seems that it occurs even if application is not in foreground though all listeners should be removed when exiting/pausing app (DBG_LISTENER).
```
PREVIOUS INCOMPLETE LOG:

04-13 20:21:50.234 E/AndroidRuntime(29211): 	at com.archos.mediaprovider.video.RemoteStateService.onHandleIntent(SourceFile:85)
04-13 20:21:50.234 E/AndroidRuntime(29211): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
04-13 20:21:50.234 E/AndroidRuntime(29211): 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-13 20:21:50.234 E/AndroidRuntime(29211): 	at android.os.Looper.loop(Looper.java:214)
04-13 20:21:50.234 E/AndroidRuntime(29211): 	at android.os.HandlerThread.run(HandlerThread.java:67)

COMPLETE LOG:

04-15 07:41:18.825 E/AndroidRuntime(18235): FATAL EXCEPTION: IntentService[RemoteStateService]
04-15 07:41:18.825 E/AndroidRuntime(18235): Process: org.courville.nova, PID: 18235
04-15 07:41:18.825 E/AndroidRuntime(18235): java.lang.StackOverflowError: stack size 1039KB
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:317)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at com.archos.environment.NetworkState.updateFrom(SourceFile:99)

04-15 07:41:18.825 E/AndroidRuntime(18235): 	at com.archos.mediacenter.utils.trakt.TraktService$2.propertyChange(SourceFile:1339)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
04-15 07:41:18.825 E/AndroidRuntime(18235): 	at com.archos.environment.NetworkState.updateFrom(SourceFile:99)

<looping>

04-15 07:41:18.829 E/AndroidRuntime(18235): 	at com.archos.mediacenter.utils.trakt.TraktService$2.propertyChange(SourceFile:1339)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at com.archos.environment.NetworkState.updateFrom(SourceFile:99)

04-15 07:41:18.829 E/AndroidRuntime(18235): 	at com.archos.mediacenter.utils.trakt.TraktService$2.propertyChange(SourceFile:1339)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
04-15 07:41:18.829 E/AndroidRuntime(18235): 	at com.archos.environment.NetworkState.updateFrom(SourceFile:99)
```

adb logcat -v color | egrep "(AppState|NetworkState|Trakt|RemoteState)"

**Comment by courville** [comment]
NetworkState stays alive even if there are no listeners...

**Comment by courville** [comment]
Should be fixed now
