### ISSUE TITLE
crash on amazon devices when doing search

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#371]
Reported by amazon test team:

> Your app has failed a test case.
> 
> Bug Description: The app crashes, force closes, hard/soft locks, or is otherwise unstable
> Steps to reproduce: 
> 1. Install and launch the app 
> 2. Navigate and select search option 
> Actual Result: Observe app exits/force closes to device home screen or is soft/hard locked 
> Expected Result: App must not experience force close, crash, or soft/hard lock while in use, even when dealing with conflicting inputs. 
> 
> Affected devices:
> Fire TV (2014)
> Fire TV Stick
> Fire TV (2015)
> Fire TV Stick with Alexa Voice Remote
> Amazon Fire TV Edition

**Comment by courville** [comment]
Fishing for traces in my acrarium:
```
java.lang.IllegalStateException: android.permission.RECORD_AUDIO required for search
	at androidx.leanback.widget.SearchBar.startRecognition(SourceFile:615)
	at androidx.leanback.app.SearchSupportFragment$4.run(SourceFile:204)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5597)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by courville** [comment]
Not anymore the case...
