### ISSUE TITLE
[Android TV Box] Crash on start

### ISSUE THREAD

**Issue by Generator** [nova-video-player/aos-AVP#393]
## Description
Fresh install on an Android TV Box (X99 Max+) with custom ROM ([SLIMBOX](https://forum.xda-developers.com/android-stick--console-computers/amlogic/project-slimbox-t4152049)), then trying to start the app imitatively crashes on start (after accepting storage access permission). 

Other video players work without issues (VLC/MX Player/Kodi/Plex)

From debugging: `E ActivityThread: Failed to find provider info for android.media.tv`

[logcat.txt](https://github.com/nova-video-player/aos-AVP/files/5533537/logcat.txt)

**Info:**
Android 9
Nova Video Player 4.49.11

**Comment by courville** [comment]
Hum custom ROM... Thanks for the logs.
It crashes when creating tv channels failing to find provider for `android.media.tv` missing from the custom ROM:
```
E ActivityThread: Failed to find provider info for android.media.tv
--------- beginning of crash
E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
E AndroidRuntime: Process: org.courville.nova, PID: 7332
E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:1583)
E AndroidRuntime: 	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.createChannel(SourceFile:367)
E AndroidRuntime: 	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.doInBackground(SourceFile:332)
E AndroidRuntime: 	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.doInBackground(SourceFile:323)[0m
E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E AndroidRuntime: 	... 4 more
```
What is the custom ROM you are using?

**Comment by phhusson** [comment]
This is a bug in the ROM, I've answered this here:
https://forum.xda-developers.com/showpost.php?p=83914869&postcount=415

**Comment by Generator** [comment]
@courville SLIMBOX ([XDA Forum Project Thread](https://forum.xda-developers.com/android-stick--console-computers/amlogic/project-slimbox-t4152049))  
However i didn't find any sources or if the OP of that thread is one of ROM developers or just an english version of 4pda.ru forum.  
Here's the forum thread from 4pda https://4pda.ru/forum/index.php?showtopic=993324  

@phhusson thanks for reporting, also check the 4pda.ru thread 

EDIT: There's two versions of the same ROM, AndroidTV and AOSP (Android 9), i'm using the AOSP version.

**Comment by courville** [comment]
Closing due to inactivity and possibly prior solving. Please reopen an issue if needed.
