### ISSUE TITLE
Android 12 beta3 crash

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#457]
Same apk run on Android 11 works but crashes on Android 12 beta3:
```
07-15 21:42:56.676 20686 20686 E AndroidRuntime: FATAL EXCEPTION: main
07-15 21:42:56.676 20686 20686 E AndroidRuntime: Process: org.courville.nova, PID: 20686
07-15 21:42:56.676 20686 20686 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "jniGetFDFromFileDescriptor" referenced by "/data/app/~~1x7jUpyYsbSGVSbjMt6jTA==/org.courville.nova-mAy-zDuNSC7mSkM5hYbxLA==/lib/arm64/libfilecoreutils.so"...
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1656)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at com.archos.filecorelibrary.samba.SambaDiscovery.<clinit>(SourceFile:564)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at com.archos.mediacenter.video.browser.filebrowsing.network.SmbBrowser.SmbRootFragment.onAttach(SourceFile:123)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performAttach(SourceFile:2922)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.attach(SourceFile:464)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:275)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:2189)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:2100)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:2002)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:3138)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(SourceFile:3072)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(SourceFile:251)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:501)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:246)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8076)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3658)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7829)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-15 21:42:56.676 20686 20686 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
```

**Comment by courville** [comment]
Cf. https://stackoverflow.com/questions/24701029/how-to-properly-pass-an-asset-filedescriptor-to-ffmpeg-using-jni-in-android
```
❯ ag jniGetFDFromFileDescriptor
native/avos/jni/libavosjni/avos_media_metadata_retriever.c
159:    int fd = jniGetFDFromFileDescriptor(env, fileDescriptor);

native/avos/jni/libavosjni/avos_media_player.c
520:    int fd = jniGetFDFromFileDescriptor(env, fileDescriptor);

native/libnativehelper/JNIHelp.cpp
337:int jniGetFDFromFileDescriptor(C_JNIEnv* env, jobject fileDescriptor) {

native/libnativehelper/include/nativehelper/JNIHelp.h
94:int jniGetFDFromFileDescriptor(C_JNIEnv* env, jobject fileDescriptor);
159:inline int jniGetFDFromFileDescriptor(JNIEnv* env, jobject fileDescriptor) {
160:    return jniGetFDFromFileDescriptor(&env->functions, fileDescriptor);

FileCoreLibrary/jni/utils/filecoreutils.cpp
19:    int outfd = jniGetFDFromFileDescriptor(jenv, out);
24:    int infd = jniGetFDFromFileDescriptor(jenv, in);
```

**Comment by courville** [comment]
Crash happens in `SambaDiscovery`: `System.loadLibrary("filecoreutils");`

Checking: `/opt/android-sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/x86_64-linux-android/bin/readelf -a ./build/intermediates/library_jni/release/jni/x86_64/libfilecoreutils.so | grep NEEDED`, we see that `libnativehelper.so` is correctly embedded:
```
/opt/android-sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/x86_64-linux-android/bin/readelf -a ./build/intermediates/library_jni/release/jni/x86_64/libfilecoreutils.so | grep NEEDED
0x0000000000000001 (NEEDED)             Shared library: [libnativehelper.so]
0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
0x0000000000000001 (NEEDED)             Shared library: [libc.so]
0x0000000000000001 (NEEDED)             Shared library: [libm.so]
0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
```

Renaming `libnativehelper` to `libnvpnativehelper` fixes the issue.
Appears to be an Android NDK/platform issue.

**Comment by courville** [comment]
Check: `/opt/android-sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64/x86_64-linux-android/bin/readelf -a ./build/intermediates/library_jni/release/jni/x86_64/libfilecoreutils.so | grep NEEDED`

**Comment by courville** [comment]
Keeping the issue open pending better fix.

**Comment by courville** [comment]
Issue created on Google IssueTracker https://issuetracker.google.com/issues/193933286
