### ISSUE TITLE
[Bug]: Nvidia Shield TV Pro - Microphone Permission not available

### ISSUE THREAD

**Issue by PcFish** [nova-video-player/aos-AVP#540]
### Problem description

Voice search does not work. Microphone Permission does not pop up. Does not show in app settings either 

Worked fine on my Chromecast w GTV.
Voice works for Gboard typing while using Nova as well as other apps.
Tried installing an older version of Nova as well and it still isn't popping for some reason

### Steps to reproduce the issue

Attempt to search using microphone button found within the app. Clicking on it does not activate microphone nor microphone permission pop-up.

### Expected behavior

Microphone to activate

### Your phone/tablet/androidTV model

Nvidia Shield TV Pro software

### Operating system version

Android 11

### Application version and app store

6.0.36-20211223.1654

### Additional system information

Nvidia Shield TV Pro software: 9.0.0
Android 11
Build RQ1A.210105.003.7094351_2914.3416

**Comment by courville** [comment]
Good point Android changed everything again... [SpeechRecognitionCallback](https://developer.android.com/reference/androidx/leanback/widget/SpeechRecognitionCallback ) is deprecated and it is automagic with [SearchSupportFragment](https://developer.android.com/reference/androidx/leanback/app/SearchSupportFragment ) like it used to be but (note to self) it was not working on FireStick cf. https://github.com/nova-video-player/aos-AVP/issues/371
Will have a look.

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-Video/commit/0b6a678c3661b861f93dda9090d2cad12bb92fc7 should be the solution. However this does not work on the shield but verified to work on the Android emulator.

**Comment by Cowboy1968** [comment]
on [v6.0.43 NON Google play internal (non public) release], Voice Search is not working at all.  I select the microphone icon and I hear a beep indicating its listening, but immediately followed by another beep indicating it stopped.

**Comment by courville** [comment]
Interestingly enough, voice search works on google chromecast (sabrina) but not on the nvidia shield with latest version of nova. The issue seems shield specific.

**Comment by courville** [comment]
OK some logs that hints toward https://stackoverflow.com/questions/65404190/speechrecognizer-wont-work-on-android-11-if-androidshareduserid-is-set linked to https://issuetracker.google.com/issues/176129030 where google says won't fix...
```
06-18 19:07:14.537  3518  5703 E AppOps  : noteOperation
06-18 19:07:14.537  3518  5703 E AppOps  : java.lang.SecurityException: Specified package archos.openmediacenter under uid 10104 but it is really -1
06-18 19:07:14.537  3518  5703 E AppOps  :      at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:3921)
06-18 19:07:14.537  3518  5703 E AppOps  :      at com.android.server.appop.AppOpsService.noteOperationUnchecked(AppOpsService.java:3065)
06-18 19:07:14.537  3518  5703 E AppOps  :      at com.android.server.appop.AppOpsService.noteProxyOperation(AppOpsService.java:3016)
06-18 19:07:14.537  3518  5703 E AppOps  :      at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:585)
06-18 19:07:14.537  3518  5703 E AppOps  :      at android.os.Binder.execTransactInternal(Binder.java:1159)
06-18 19:07:14.537  3518  5703 E AppOps  :      at android.os.Binder.execTransact(Binder.java:1123)
```
Issue apparently is that nova uses sharedUserId in AndroidManifest.
Note that sharedUserId cannot be removed otherwise all users will not be able to upgrade.
I am afraid that there is no real solution.

Full log:
```
06-18 19:13:39.717  9951 10683 I katniss_search_AudioRecordSource: #audio# create audio stream for audio record source(identity(xhq@e8615ad), recordId(121))
06-18 19:13:39.719  3278  4227 I APM::AudioPolicyEngine: getDeviceForInputSource() RVS capable devices not present. Reset RVSRequest.                   RVSRequest=0
06-18 19:13:39.720  3518  3979 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.720  3205  3472 E nvaudio_hw: nvaudio_dev_create_audio_patch(): handle generated, handle:7
06-18 19:13:39.720  3518  4863 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.722  3518  4863 I SoundTriggerMiddlewareLogging: setCaptureState[this=com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareImpl@86a9900, caller=1041/3278](true)
06-18 19:13:39.723  3205  3472 E FMQ     : grantorIdx must be less than 3
06-18 19:13:39.723  3205  3472 E FMQ     : grantorIdx must be less than 3
06-18 19:13:39.723  3278 10697 E FMQ     : grantorIdx must be less than 3
06-18 19:13:39.723  3278 10697 E FMQ     : grantorIdx must be less than 3
06-18 19:13:39.724  3205 10699 E nvaudio_route: Failed to apply path builtin-mic.
06-18 19:13:39.725  9951  9951 I katniss_search_NetworkSpeechRecognizer: Online recognizer - start listening
06-18 19:13:39.726  3518  4863 I system_server: oneway function results will be dropped but finished with status OK and parcel size 8
06-18 19:13:39.727  9951  9951 I katniss_search_SodaSpeechRecognizer: Offline recognizer - start listening
06-18 19:13:39.727  9951  9951 I katniss_search_SodaSpeechRecognizer: Initialize Soda [locale: fr-FR]
06-18 19:13:39.727  9951 10684 W katniss_search_OggOpusInputStream: Beginning load of ogg_opus_encoder...
06-18 19:13:39.728  9951 10000 E katniss_search_SodaSpeechRecognizer: Soda recognizer failed to initialize: ConfigStatus 3!
06-18 19:13:39.729  9951 10684 W katniss_search_OggOpusInputStream: ogg_opus_encoder (null) was loaded normally!
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: S3Request:
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: # ajdh@ff5ad4e7
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [293000] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [293100] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [294000] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [294500] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [29735924] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: [77499489] {
06-18 19:13:39.729  9951 10683 I katniss_search_BaseS3HeaderProducer: }
06-18 19:13:39.731  9951  9988 I katniss_search_AudioEventsHolder: #audio# audio request client(token(1136391272)) session(token(1593180286)) start listening status(OPENED)
06-18 19:13:39.731  9951  9986 I katniss_search_xpb: #audio# AudioRequestListeningSession start listening status: OPENED
06-18 19:13:39.732  9951  9988 I katniss_search_MicUpdateReporter: #audio# reportMicUpdate
06-18 19:13:39.732  3518  3979 W AppOps  : Noting op not finished: uid 10006 pkg com.google.android.katniss code 27 startTime of in progress event=1687108419718
06-18 19:13:39.733  3518  3979 E AppOps  : noteOperation
06-18 19:13:39.733  3518  3979 E AppOps  : java.lang.SecurityException: Specified package archos.openmediacenter under uid 10104 but it is really -1
06-18 19:13:39.733  3518  3979 E AppOps  : 	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:3921)
06-18 19:13:39.733  3518  3979 E AppOps  : 	at com.android.server.appop.AppOpsService.noteOperationUnchecked(AppOpsService.java:3065)
06-18 19:13:39.733  3518  3979 E AppOps  : 	at com.android.server.appop.AppOpsService.noteProxyOperation(AppOpsService.java:3016)
06-18 19:13:39.733  3518  3979 E AppOps  : 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:585)
06-18 19:13:39.733  3518  3979 E AppOps  : 	at android.os.Binder.execTransactInternal(Binder.java:1159)
06-18 19:13:39.733  3518  3979 E AppOps  : 	at android.os.Binder.execTransact(Binder.java:1123)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: Failed uploading data to S3
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: xny: Initialization failed
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at xib.a(PG:7)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at xib.read(PG:5)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at xib.read(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at zbj.read(PG:3)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at aevh.c(PG:4)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at kzs.a(PG:105)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at acae.a(PG:3)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at afmy.c(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at afna.run(PG:9)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at rvs.run(PG:1)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at rux.run(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at java.lang.Thread.run(Thread.java:923)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at rvx.run(PG:5)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: Caused by: java.lang.SecurityException: Proxy package com.google.android.katniss from uid 10006 or calling package archos.openmediacenter from uid 10104 not allowed to perform RECORD_AUDIO
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:7514)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at android.app.AppOpsManager.noteProxyOp(AppOpsManager.java:7541)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at laf.p(PG:17)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at laf.n(PG:4)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at lbp.a(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at acae.a(PG:3)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at afmy.c(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at afna.run(PG:9)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at rvs.run(PG:1)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	at rva.run(PG:2)
06-18 19:13:39.734  9951  9986 W katniss_search_NetworkSpeechRecognizer: 	... 2 more
06-18 19:13:39.734  9951  9986 I cr_CronetUrlRequestContext: destroyNativeStreamLocked org.chromium.net.impl.CronetBidirectionalStream@5a3f863
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: Transcription error
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: kxw
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at kzt.a(PG:7)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at acal.a(PG:4)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at afpg.run(PG:8)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at rvs.run(PG:1)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at rva.run(PG:2)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at java.lang.Thread.run(Thread.java:923)
06-18 19:13:39.735  9951  9988 W katniss_search_NetworkSpeechRecognizer: 	at rvx.run(PG:5)
06-18 19:13:39.735  9951  9986 W katniss_search_RecognitionClient: #onError space agsa_transcription_NETWORK_REQUEST_BUILDING code -1!
06-18 19:13:39.736  9951  9986 I katniss_search_ARCSession: #audio# stop(reason(CLIENT_REQUESTED)) listening audio request client(token(1136391272)) session(token(1593180286))
06-18 19:13:39.736  9951  9986 I katniss_search_ARCSessionMgr: #audio# stop(reason(CLIENT_REQUESTED)) listening audio request session(token(1593180286))
06-18 19:13:39.736  9951  9986 I katniss_search_SourceMgr: #audio# stopListening
06-18 19:13:39.736  9951  9986 I katniss_search_SourceSequencer: #audio# close audio source(xhq@e8615ad)
06-18 19:13:39.736  9951  9986 I katniss_search_AFCSession: #audio# release audio focus session(token(4))
06-18 19:13:39.736  9951 10683 I katniss_search_AudioRecordSource: #audio# close audio source(identity(xhq@e8615ad), recordId(121))
06-18 19:13:39.736  9951 10684 I katniss_search_FirstByteReporter: #audio# mark first byte read result as non-determined
06-18 19:13:39.737  3518  3979 I MediaFocusControl: abandonAudioFocus() from uid/pid 10006/9951 clientId=android.media.AudioManager@2b24543xgg@d4902c4
06-18 19:13:39.737  9456  9456 W SearchBar: recognizer client error
06-18 19:13:39.737  3518  4863 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.738  9951  9986 I katniss_search_AudioLibraryAudioController: Audio focus releasing status: RELEASED
06-18 19:13:39.738  9951  9986 I katniss_search_AudioEventsHolder: #audio# audio focus session(token(4)) release status(RELEASED)
06-18 19:13:39.738  9951 10684 I katniss_search_BytesAccessorBuffer: #audio# mark buffer(xfo@ad3b7bf) closed, available bytes(0)
06-18 19:13:39.744  3205  3472 E nvaudio_route: Failed to reset path builtin-mic.
06-18 19:13:39.749  3278  5835 I APM_AudioPolicyManager: getOutputForAttrInt() device {type:0x400,@:}, sampling rate 16000, format 0x1, channel mask 0x1, flags 0 stream AUDIO_STREAM_NOTIFICATION
06-18 19:13:39.749  3205  3472 I nvaudio_hw: prop_get:hw_dev->is_native_sample_rate:0
06-18 19:13:39.749  3518  4863 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.750  3278  5835 I APM_AudioPolicyManager: getOutputForAttrInt returns output 13 selectedDeviceId 23 for device {type:0x400,@:}, sampling rate 16000, format 0x1, channel mask 0x1, flags 0 stream AUDIO_STREAM_NOTIFICATION
06-18 19:13:39.750  3278  5835 D AudioFlinger: Client defaulted notificationFrames to 3500 for frameCount 7000
06-18 19:13:39.751  3278  5835 D AF::TrackHandle: OpPlayAudio: track:70 usage:10 not muted
06-18 19:13:39.752  3518  5710 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.752  3518  5710 I chatty  : uid=1000(system) Binder:3518_14 identical 1 line
06-18 19:13:39.753  3518  5710 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
06-18 19:13:39.753  3518  4863 I SoundTriggerMiddlewareLogging: setCaptureState[this=com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareImpl@86a9900, caller=1041/3278](false)
06-18 19:13:39.754  4096 10690 D AtvRemote.AudioTrackWrapper: AudioTrack paused in 0ms (underrun count: 0)
06-18 19:13:39.756  9951  9988 I katniss_search_AudioEventsHolder: #audio# audio request client(token(1136391272)) session(token(1593180286)) stop listening status(CLOSED)
06-18 19:13:39.756  9951  9986 I katniss_search_xpb: #audio# AudioRequestListeningSession stop listening status: CLOSED
06-18 19:13:39.756  9951  9988 I katniss_search_AudioLibraryAudioController: Mic closing result: # xbw@7bca4
06-18 19:13:39.756  9951  9986 I katniss_search_MicUpdateReporter: #audio# reportMicUpdate
06-18 19:13:39.757  3518  3979 I SoundTriggerMiddlewareLogging: setCaptureState[this=com.android.server.soundtrigger_middleware.SoundTriggerMiddlewareImpl@86a9900, caller=1041/3278](false)
06-18 19:13:39.757  3518  5710 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4

```

**Comment by courville** [comment]
@Cowboy1968 when 6.2.16 will be published on github, please check that if you deinstall/reinstall nova with this version it solves your issue.

**Comment by Cowboy1968** [comment]
Awesome thanks
