### ISSUE TITLE
[Bug]: SQLiteConstraintException during scrape from older version

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#570]
### Problem description

Seems to be a regression: `SHOW.name_show` UNIQUE constraint fails.
Seems related to recent show date management.

### Steps to reproduce the issue

Scrape new content.

### Your phone/tablet/androidTV model

all

### Operating system version

all

### Application version and app store

v6.x

### Debug logs

```
E/AndroidRuntime( 8487): Process: org.courville.nova, PID: 8487
E/AndroidRuntime( 8487): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SHOW.name_show (code 2067 SQLITE_CONSTRAINT_UNIQUE)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:831)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1704)
E/AndroidRuntime( 8487): 	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1650)
E/AndroidRuntime( 8487): 	at com.archos.mediaprovider.video.ScraperProvider.update(SourceFile:1249)
E/AndroidRuntime( 8487): 	at com.archos.mediaprovider.video.VideoProvider.update(SourceFile:607)
E/AndroidRuntime( 8487): 	at android.content.ContentProvider$Transport.update(ContentProvider.java:420)
E/AndroidRuntime( 8487): 	at android.content.ContentResolver.update(ContentResolver.java:1993)
E/AndroidRuntime( 8487): 	at com.archos.mediascraper.ShowTags.save(SourceFile:197)
E/AndroidRuntime( 8487): 	at com.archos.mediascraper.EpisodeTags.save(SourceFile:122)
E/AndroidRuntime( 8487): 	at com.archos.mediascraper.AutoScrapeService$3.run(SourceFile:509)
```

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-MediaLib/commit/03458d4d38b540d79cff31ff7af86bf9922e3833 for ScraperTables showName should be unique (comment).
It is likely to be a side effect while fixing https://github.com/nova-video-player/aos-AVP/issues/479 following this specific commit https://github.com/nova-video-player/aos-MediaLib/commit/12ac6f816a58fca7e536659e087bda40e2698b2a
This is an issue since it might cause crashes when not reinstalling from scratch.

**Comment by courville** [comment]
Again a problem with a corner case happening with Hawkeye 2021 tvshow and Hawkeye 1994 tvshow with exact same name. A back and forth rename on the overall show creates a crash. Do implement proper detection logic for reboots and when to update/create tvshow name or tvshow name with date.
