### ISSUE TITLE
gradle 7.5 migration issue

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#894]
Cf. https://github.com/gradle/gradle/issues/21452 gradle 7.5 migration was causing project build issues.
Now it compiles fine with latest gradle plugin it seems but when launching application and going to upnp on phone, I get:
```
E/AndroidRuntime( 9873): FATAL EXCEPTION: main
E/AndroidRuntime( 9873): Process: org.courville.nova, PID: 9873
E/AndroidRuntime( 9873): java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/servlet/http/HttpServlet;
E/AndroidRuntime( 9873): 	at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createStreamServer(AndroidUpnpServiceConfiguration.java:110)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:91)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
E/AndroidRuntime( 9873): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4482)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2157)
E/AndroidRuntime( 9873): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9873): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 9873): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/AndroidRuntime( 9873): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9873): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 9873): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 9873): Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.servlet.http.HttpServlet" on path: DexPathList[[zip file "/data/app/~~l9flafUo-Y_R0USqxx8HWQ==/org.courville.nova-0v3yQKZt59Fu_r7LAtnawA==/base.apk"],nativeLibraryDirectories=[/data/app/~~l9flafUo-Y_R0USqxx8HWQ==/org.courville.nova-0v3yQKZt59Fu_r7LAtnawA==/lib/arm64, /data/app/~~l9flafUo-Y_R0USqxx8HWQ==/org.courville.nova-0v3yQKZt59Fu_r7LAtnawA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 9873): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime( 9873): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 9873): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 9873): 	... 17 more
```
It is related to cling dependency to jetty old versions:
```    
    implementation group: 'org.eclipse.jetty', name: 'jetty-server', version:'8.1.22.v20160922'
    implementation group: 'org.eclipse.jetty', name: 'jetty-servlet', version:'8.1.22.v20160922'
    implementation group: 'org.eclipse.jetty', name: 'jetty-client', version:'8.1.22.v20160922'
```
And cling on Android is bound to use jetty cf. https://github.com/4thline/cling/blob/master/core/src/manual/advanced/transports.xhtml
Any attempt to upgrade beyond jetty 8.1 fails (e.g. 9.x) and would probably require more rewriting on cling side:
```
E/AndroidRuntime( 8333): FATAL EXCEPTION: main
E/AndroidRuntime( 8333): Process: org.courville.nova, PID: 8333
E/AndroidRuntime( 8333): java.lang.NoSuchMethodError: No virtual method setGracefulShutdown(I)V in class Lorg/eclipse/jetty/server/Server; or its super classes (declaration of 'org.eclipse.jetty.server.Server' appears in /data/app/~~5Ih3AEI64c70zGn9hpbgng==/org.courville.nova-o33-bptGaw29HxFLXXqdLw==/base.apk!classes32.dex)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.resetServer(JettyServletContainer.java:166)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<init>(JettyServletContainer.java:57)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<clinit>(JettyServletContainer.java:55)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createStreamServer(AndroidUpnpServiceConfiguration.java:110)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:91)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
E/AndroidRuntime( 8333): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4482)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2157)
E/AndroidRuntime( 8333): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8333): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8333): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8333): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/AndroidRuntime( 8333): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Workarounds for https://github.com/gradle/gradle/issues/21452 requires local maven repo tweaking which is not really feasible.
TODO: now that it builds investigate `NoClassDefFoundError` error.

**Comment by courville** [comment]
See https://stackoverflow.com/questions/75140684/why-does-gradle-7-4-bin-zip-prevent-me-from-using-javax-servlet

**Comment by courville** [comment]
It is fixed by adding to `build.gradle`:
```
    implementation group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
```
and using gradle 7.5 and AGP 7.4.2

**Comment by courville** [comment]
Reopening since it does not work in debug (works in release though):
```
> Task :stripAmazonDebugDebugSymbols

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mergeExtDexAmazonDebug'.
> Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
   > Failed to transform jetty-servlet-8.1.22.v20160922.jar (org.eclipse.jetty:jetty-servlet:8.1.22.v20160922) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
         > No variants of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 match the consumer attributes:
             - org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 configuration runtime declares a runtime of a component:
                 - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
                 - Other compatible attributes:
                     - Doesn't say anything about asm-transformed-variant (required 'NONE')
                     - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
                     - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                     - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:amazon (required 'amazon')
                     - Doesn't say anything about dexing-enable-desugaring (required 'true')
                     - Doesn't say anything about dexing-enable-jacoco-instrumentation (required 'false')
                     - Doesn't say anything about dexing-is-debuggable (required 'true')
                     - Doesn't say anything about dexing-min-sdk (required '21')
                     - Doesn't say anything about its target Java environment (preferred optimized for Android)
   > Failed to transform jetty-security-8.1.22.v20160922.jar (org.eclipse.jetty:jetty-security:8.1.22.v20160922) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
         > No variants of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 match the consumer attributes:
             - org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 configuration runtime declares a runtime of a component:
                 - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
                 - Other compatible attributes:
                     - Doesn't say anything about asm-transformed-variant (required 'NONE')
                     - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
                     - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                     - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:amazon (required 'amazon')
                     - Doesn't say anything about dexing-enable-desugaring (required 'true')
                     - Doesn't say anything about dexing-enable-jacoco-instrumentation (required 'false')
                     - Doesn't say anything about dexing-is-debuggable (required 'true')
                     - Doesn't say anything about dexing-min-sdk (required '21')
                     - Doesn't say anything about its target Java environment (preferred optimized for Android)
   > Failed to transform jetty-server-8.1.22.v20160922.jar (org.eclipse.jetty:jetty-server:8.1.22.v20160922) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
         > No variants of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 match the consumer attributes:
             - org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 configuration runtime declares a runtime of a component:
                 - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
                 - Other compatible attributes:
                     - Doesn't say anything about asm-transformed-variant (required 'NONE')
                     - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
                     - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                     - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:amazon (required 'amazon')
                     - Doesn't say anything about dexing-enable-desugaring (required 'true')
                     - Doesn't say anything about dexing-enable-jacoco-instrumentation (required 'false')
                     - Doesn't say anything about dexing-is-debuggable (required 'true')
                     - Doesn't say anything about dexing-min-sdk (required '21')
                     - Doesn't say anything about its target Java environment (preferred optimized for Android)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':mergeLibDexAmazonDebug'.
> Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
   > Failed to transform classes.jar (project :MediaLib) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.gradle.internal.attributes.VariantAttr=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':amazonDebugRuntimeClasspath'.
         > No variants of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 match the consumer attributes:
             - org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 configuration runtime declares a runtime of a component:
                 - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
                 - Other compatible attributes:
                     - Doesn't say anything about asm-transformed-variant (required 'NONE')
                     - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
                     - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                     - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:amazon (required 'amazon')
                     - Doesn't say anything about dexing-enable-desugaring (required 'true')
                     - Doesn't say anything about dexing-enable-jacoco-instrumentation (required 'false')
                     - Doesn't say anything about dexing-is-debuggable (required 'true')
                     - Doesn't say anything about dexing-min-sdk (required '21')
                     - Doesn't say anything about its target Java environment (preferred optimized for Android)

```

**Comment by sugar1yi1github** [comment]
最终是怎么解决的呢？

**Comment by courville** [comment]
@sugar1yi1github excluding javax.servlet as refererenced in https://github.com/nova-video-player/aos-MediaLib/commit/e63d86e618f322f2730b5fe6de38f6c2752aa047

**Comment by sugar1yi1github** [comment]
Thank you in advance. Your method can indeed reduce exception reporting, but it still leaves some problems:
Execution failed for task ':app:mergeDexRelease'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Failed to transform classes.jar (project :connectDetectSDK) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, com.android.build.api.attributes.AgpVersionAttr=7.4.2, com.android.build.api.attributes.BuildTypeAttr=release, com.android.build.gradle.internal.attributes.VariantAttr=release, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=false, dexing-min-sdk=21, org.gradle.category=library, org.gradle.jvm.environment=android, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
         > No variants of org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 match the consumer attributes:
             - org.eclipse.jetty.orbit:javax.servlet:3.0.0.v201112011016 configuration runtime declares a runtime of a component:
                 - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
                 - Other compatible attributes:
                     - Doesn't say anything about asm-transformed-variant (required 'NONE')
                     - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.4.2')
                     - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                     - Doesn't say anything about dexing-enable-desugaring (required 'true')
                     - Doesn't say anything about dexing-enable-jacoco-instrumentation (required 'false')
                     - Doesn't say anything about dexing-is-debuggable (required 'false')
                     - Doesn't say anything about dexing-min-sdk (required '21')
                     - Doesn't say anything about its target Java environment (preferred optimized for Android)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by sugar1yi1github** [comment]
I looked at the exceptions you encountered before, and I also have this one. I would like to ask how you solved it.

**Comment by sugar1yi1github** [comment]
Thank you very much. Your method perfectly solved the problem I encountered.

**Comment by courville** [comment]
@sugar1yi1github, it is best that you realign with current code if you want to avoid problems.
Out of curiosity, what is your usage of nova codebase?

**Comment by sugar1yi1github** [comment]
I encountered this problem when using the Cling library. I mainly wanted to develop a diagnostic tool to determine whether my screencasting device can be found in the LAN.I encountered this problem when using the Cling library. I mainly wanted to develop a diagnostic tool to determine whether my screencasting device can be found in the LAN.

**Comment by sugar1yi1github** [comment]
@courville 
I encountered this problem when using the Cling library. I mainly wanted to develop a diagnostic tool to determine whether my screencasting device can be found in the LAN.
