### ISSUE TITLE
ShowTags exception when trying to update NFO

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#91]
Seems to be when updating data on tv show if needed in EpisodeTags.java `mShowTags.save(context, videoId);` when pushing data into database in ShowTags.java `cr.applyBatch(ScraperStore.AUTHORITY, allOperations);`
```
03-24 09:27:46.644 22663 23043 D ShowTags: Exception :android.content.OperationApplicationException: insert failed
03-24 09:27:46.644 22663 23043 D ShowTags: android.content.OperationApplicationException: insert failed
03-24 09:27:46.644 22663 23043 D ShowTags:      at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:292)
03-24 09:27:46.644 22663 23043 D ShowTags:      at com.archos.mediaprovider.video.VideoProvider.applyBatch(VideoProvider.java:1073)
03-24 09:27:46.644 22663 23043 D ShowTags:      at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:320)
03-24 09:27:46.644 22663 23043 D ShowTags:      at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:474)
03-24 09:27:46.644 22663 23043 D ShowTags:      at android.content.ContentResolver.applyBatch(ContentResolver.java:1626)
03-24 09:27:46.644 22663 23043 D ShowTags:      at com.archos.mediascraper.ShowTags.save(ShowTags.java:291)
03-24 09:27:46.644 22663 23043 D ShowTags:      at com.archos.mediascraper.EpisodeTags.save(EpisodeTags.java:122)
03-24 09:27:46.644 22663 23043 D ShowTags:      at com.archos.mediascraper.AutoScrapeService$3.run(AutoScrapeService.java:276)
```

**Comment by courville** [comment]
Closing due to inactivity and possibly prior solving. Please reopen an issue if needed.
