### ISSUE TITLE
DeleteFileAndVobCallback crash when there is a too large task

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#95]
```
03-24 15:26:38.495 11130 11167 E AndroidRuntime: FATAL EXCEPTION: ImportWorker
03-24 15:26:38.495 11130 11167 E AndroidRuntime: Process: org.courville.nova, PID: 11130
03-24 15:26:38.495 11130 11167 E AndroidRuntime: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=16
916, totalRows=2161
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:895)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:157)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:237)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.database.CursorWrapper.moveToNext(CursorWrapper.java:202)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at com.archos.mediaprovider.CustomCursorFactory$CustomCursor.moveToNext(CustomCursorFactory.java:82)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at com.archos.mediaprovider.video.VideoStoreImportService.processDeleteFileAndVobCallback(VideoStoreImportService.java:352)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at com.archos.mediaprovider.video.VideoStoreImportService.doImport(VideoStoreImportService.java:331)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at com.archos.mediaprovider.video.VideoStoreImportService.handleMessage(VideoStoreImportService.java:275)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
03-24 15:26:38.495 11130 11167 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by courville** [comment]
Dupplicate https://github.com/nova-video-player/aos-AVP/issues/275
